export default {
  'menu.app.pma': 'phpMyAdmin Management',
  'app.pma.manager.title': 'phpMyAdmin - {name}',
  'app.pma.tab.info': 'Instance Info',
  'app.pma.tab.port': 'Port Settings',
  'app.pma.tab.servers': 'Server List',
  'app.pma.info.name': 'Name',
  'app.pma.info.version': 'Version',
  'app.pma.info.port': 'Port',
  'app.pma.info.status': 'Status',
  'app.pma.button.refreshStatus': 'Refresh Status',
  'app.pma.button.start': 'Start',
  'app.pma.button.stop': 'Stop',
  'app.pma.button.restart': 'Restart',
  'app.pma.button.changePort': 'Change Port',
  'app.pma.port.label': 'Access Port',
  'app.pma.port.placeholder': 'Please enter port',
  'app.pma.servers.searchPlaceholder': 'Search by name',
  'app.pma.servers.verbose': 'Name',
  'app.pma.servers.host': 'Host',
  'app.pma.servers.port': 'Port',
  'app.pma.servers.addTitle': 'Add Server',
  'app.pma.servers.editTitle': 'Edit Server',
  'app.pma.servers.form.verbose': 'Display Name',
  'app.pma.servers.form.host': 'Host',
  'app.pma.servers.form.port': 'Port',
  'app.pma.message.loadComposeFailed': 'Failed to load instance info',
  'app.pma.message.loadServersFailed': 'Failed to load server list',
  'app.pma.message.operationSuccess': 'Operation {operation} succeeded',
  'app.pma.message.operationFailed': 'Operation {operation} failed',
  'app.pma.message.portChangeSuccess': 'Port changed successfully',
  'app.pma.message.portChangeFailed': 'Port change failed',
  'app.pma.message.refreshSuccess': 'Refresh succeeded',
  'app.pma.message.refreshFailed': 'Refresh failed',
};
