// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.33.0
// 	protoc        v6.31.1
// source: pma.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PmaCommonResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Success bool   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error   string `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
}

func (x *PmaCommonResponse) Reset() {
	*x = PmaCommonResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pma_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PmaCommonResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PmaCommonResponse) ProtoMessage() {}

func (x *PmaCommonResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pma_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PmaCommonResponse.ProtoReflect.Descriptor instead.
func (*PmaCommonResponse) Descriptor() ([]byte, []int) {
	return file_pma_proto_rawDescGZIP(), []int{0}
}

func (x *PmaCommonResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *PmaCommonResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type PmaGetComposesRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	HostId   uint32 `protobuf:"varint,1,opt,name=host_id,json=hostId,proto3" json:"host_id,omitempty"`
	Page     int32  `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`
	PageSize int32  `protobuf:"varint,3,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
}

func (x *PmaGetComposesRequest) Reset() {
	*x = PmaGetComposesRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pma_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PmaGetComposesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PmaGetComposesRequest) ProtoMessage() {}

func (x *PmaGetComposesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pma_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PmaGetComposesRequest.ProtoReflect.Descriptor instead.
func (*PmaGetComposesRequest) Descriptor() ([]byte, []int) {
	return file_pma_proto_rawDescGZIP(), []int{1}
}

func (x *PmaGetComposesRequest) GetHostId() uint32 {
	if x != nil {
		return x.HostId
	}
	return 0
}

func (x *PmaGetComposesRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *PmaGetComposesRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type PmaGetComposesResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Total int64              `protobuf:"varint,1,opt,name=total,proto3" json:"total,omitempty"`
	Items []*PmaComposesInfo `protobuf:"bytes,2,rep,name=items,proto3" json:"items,omitempty"`
}

func (x *PmaGetComposesResponse) Reset() {
	*x = PmaGetComposesResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pma_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PmaGetComposesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PmaGetComposesResponse) ProtoMessage() {}

func (x *PmaGetComposesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pma_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PmaGetComposesResponse.ProtoReflect.Descriptor instead.
func (*PmaGetComposesResponse) Descriptor() ([]byte, []int) {
	return file_pma_proto_rawDescGZIP(), []int{2}
}

func (x *PmaGetComposesResponse) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *PmaGetComposesResponse) GetItems() []*PmaComposesInfo {
	if x != nil {
		return x.Items
	}
	return nil
}

type PmaComposesInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name    string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Version string `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	Port    string `protobuf:"bytes,3,opt,name=port,proto3" json:"port,omitempty"`
	Status  string `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"`
}

func (x *PmaComposesInfo) Reset() {
	*x = PmaComposesInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pma_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PmaComposesInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PmaComposesInfo) ProtoMessage() {}

func (x *PmaComposesInfo) ProtoReflect() protoreflect.Message {
	mi := &file_pma_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PmaComposesInfo.ProtoReflect.Descriptor instead.
func (*PmaComposesInfo) Descriptor() ([]byte, []int) {
	return file_pma_proto_rawDescGZIP(), []int{3}
}

func (x *PmaComposesInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *PmaComposesInfo) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *PmaComposesInfo) GetPort() string {
	if x != nil {
		return x.Port
	}
	return ""
}

func (x *PmaComposesInfo) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type PmaOperationRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	HostId    uint32 `protobuf:"varint,1,opt,name=host_id,json=hostId,proto3" json:"host_id,omitempty"`
	Name      string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Operation string `protobuf:"bytes,3,opt,name=operation,proto3" json:"operation,omitempty"`
}

func (x *PmaOperationRequest) Reset() {
	*x = PmaOperationRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pma_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PmaOperationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PmaOperationRequest) ProtoMessage() {}

func (x *PmaOperationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pma_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PmaOperationRequest.ProtoReflect.Descriptor instead.
func (*PmaOperationRequest) Descriptor() ([]byte, []int) {
	return file_pma_proto_rawDescGZIP(), []int{4}
}

func (x *PmaOperationRequest) GetHostId() uint32 {
	if x != nil {
		return x.HostId
	}
	return 0
}

func (x *PmaOperationRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *PmaOperationRequest) GetOperation() string {
	if x != nil {
		return x.Operation
	}
	return ""
}

type PmaSetPortRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	HostId uint32 `protobuf:"varint,1,opt,name=host_id,json=hostId,proto3" json:"host_id,omitempty"`
	Name   string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Port   string `protobuf:"bytes,3,opt,name=port,proto3" json:"port,omitempty"`
}

func (x *PmaSetPortRequest) Reset() {
	*x = PmaSetPortRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pma_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PmaSetPortRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PmaSetPortRequest) ProtoMessage() {}

func (x *PmaSetPortRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pma_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PmaSetPortRequest.ProtoReflect.Descriptor instead.
func (*PmaSetPortRequest) Descriptor() ([]byte, []int) {
	return file_pma_proto_rawDescGZIP(), []int{5}
}

func (x *PmaSetPortRequest) GetHostId() uint32 {
	if x != nil {
		return x.HostId
	}
	return 0
}

func (x *PmaSetPortRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *PmaSetPortRequest) GetPort() string {
	if x != nil {
		return x.Port
	}
	return ""
}

type PmaGetServersRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	HostId   uint32 `protobuf:"varint,1,opt,name=host_id,json=hostId,proto3" json:"host_id,omitempty"`
	Name     string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Page     int32  `protobuf:"varint,3,opt,name=page,proto3" json:"page,omitempty"`
	PageSize int32  `protobuf:"varint,4,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
}

func (x *PmaGetServersRequest) Reset() {
	*x = PmaGetServersRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pma_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PmaGetServersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PmaGetServersRequest) ProtoMessage() {}

func (x *PmaGetServersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pma_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PmaGetServersRequest.ProtoReflect.Descriptor instead.
func (*PmaGetServersRequest) Descriptor() ([]byte, []int) {
	return file_pma_proto_rawDescGZIP(), []int{6}
}

func (x *PmaGetServersRequest) GetHostId() uint32 {
	if x != nil {
		return x.HostId
	}
	return 0
}

func (x *PmaGetServersRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *PmaGetServersRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *PmaGetServersRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type PmaGetServersResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Total int64            `protobuf:"varint,1,opt,name=total,proto3" json:"total,omitempty"`
	Items []*PmaServerInfo `protobuf:"bytes,2,rep,name=items,proto3" json:"items,omitempty"`
}

func (x *PmaGetServersResponse) Reset() {
	*x = PmaGetServersResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pma_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PmaGetServersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PmaGetServersResponse) ProtoMessage() {}

func (x *PmaGetServersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pma_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PmaGetServersResponse.ProtoReflect.Descriptor instead.
func (*PmaGetServersResponse) Descriptor() ([]byte, []int) {
	return file_pma_proto_rawDescGZIP(), []int{7}
}

func (x *PmaGetServersResponse) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *PmaGetServersResponse) GetItems() []*PmaServerInfo {
	if x != nil {
		return x.Items
	}
	return nil
}

type PmaServerInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Verbose string `protobuf:"bytes,1,opt,name=verbose,proto3" json:"verbose,omitempty"`
	Host    string `protobuf:"bytes,2,opt,name=host,proto3" json:"host,omitempty"`
	Port    string `protobuf:"bytes,3,opt,name=port,proto3" json:"port,omitempty"`
}

func (x *PmaServerInfo) Reset() {
	*x = PmaServerInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pma_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PmaServerInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PmaServerInfo) ProtoMessage() {}

func (x *PmaServerInfo) ProtoReflect() protoreflect.Message {
	mi := &file_pma_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PmaServerInfo.ProtoReflect.Descriptor instead.
func (*PmaServerInfo) Descriptor() ([]byte, []int) {
	return file_pma_proto_rawDescGZIP(), []int{8}
}

func (x *PmaServerInfo) GetVerbose() string {
	if x != nil {
		return x.Verbose
	}
	return ""
}

func (x *PmaServerInfo) GetHost() string {
	if x != nil {
		return x.Host
	}
	return ""
}

func (x *PmaServerInfo) GetPort() string {
	if x != nil {
		return x.Port
	}
	return ""
}

type PmaAddServerRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	HostId  uint32 `protobuf:"varint,1,opt,name=host_id,json=hostId,proto3" json:"host_id,omitempty"`
	Name    string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Verbose string `protobuf:"bytes,3,opt,name=verbose,proto3" json:"verbose,omitempty"`
	Host    string `protobuf:"bytes,4,opt,name=host,proto3" json:"host,omitempty"`
	Port    string `protobuf:"bytes,5,opt,name=port,proto3" json:"port,omitempty"`
}

func (x *PmaAddServerRequest) Reset() {
	*x = PmaAddServerRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pma_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PmaAddServerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PmaAddServerRequest) ProtoMessage() {}

func (x *PmaAddServerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pma_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PmaAddServerRequest.ProtoReflect.Descriptor instead.
func (*PmaAddServerRequest) Descriptor() ([]byte, []int) {
	return file_pma_proto_rawDescGZIP(), []int{9}
}

func (x *PmaAddServerRequest) GetHostId() uint32 {
	if x != nil {
		return x.HostId
	}
	return 0
}

func (x *PmaAddServerRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *PmaAddServerRequest) GetVerbose() string {
	if x != nil {
		return x.Verbose
	}
	return ""
}

func (x *PmaAddServerRequest) GetHost() string {
	if x != nil {
		return x.Host
	}
	return ""
}

func (x *PmaAddServerRequest) GetPort() string {
	if x != nil {
		return x.Port
	}
	return ""
}

type PmaRemoveServerRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	HostId uint32 `protobuf:"varint,1,opt,name=host_id,json=hostId,proto3" json:"host_id,omitempty"`
	Name   string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Host   string `protobuf:"bytes,3,opt,name=host,proto3" json:"host,omitempty"`
	Port   string `protobuf:"bytes,4,opt,name=port,proto3" json:"port,omitempty"`
}

func (x *PmaRemoveServerRequest) Reset() {
	*x = PmaRemoveServerRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pma_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PmaRemoveServerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PmaRemoveServerRequest) ProtoMessage() {}

func (x *PmaRemoveServerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pma_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PmaRemoveServerRequest.ProtoReflect.Descriptor instead.
func (*PmaRemoveServerRequest) Descriptor() ([]byte, []int) {
	return file_pma_proto_rawDescGZIP(), []int{10}
}

func (x *PmaRemoveServerRequest) GetHostId() uint32 {
	if x != nil {
		return x.HostId
	}
	return 0
}

func (x *PmaRemoveServerRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *PmaRemoveServerRequest) GetHost() string {
	if x != nil {
		return x.Host
	}
	return ""
}

func (x *PmaRemoveServerRequest) GetPort() string {
	if x != nil {
		return x.Port
	}
	return ""
}

var File_pma_proto protoreflect.FileDescriptor

var file_pma_proto_rawDesc = []byte{
	0x0a, 0x09, 0x70, 0x6d, 0x61, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x22, 0x43, 0x0a, 0x11, 0x50, 0x6d, 0x61, 0x43, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65,
	0x73, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73,
	0x73, 0x12, 0x14, 0x0a, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x22, 0x61, 0x0a, 0x15, 0x50, 0x6d, 0x61, 0x47, 0x65,
	0x74, 0x43, 0x6f, 0x6d, 0x70, 0x6f, 0x73, 0x65, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x17, 0x0a, 0x07, 0x68, 0x6f, 0x73, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0d, 0x52, 0x06, 0x68, 0x6f, 0x73, 0x74, 0x49, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x70, 0x61, 0x67,
	0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x70, 0x61, 0x67, 0x65, 0x12, 0x1b, 0x0a,
	0x09, 0x70, 0x61, 0x67, 0x65, 0x5f, 0x73, 0x69, 0x7a, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x08, 0x70, 0x61, 0x67, 0x65, 0x53, 0x69, 0x7a, 0x65, 0x22, 0x5c, 0x0a, 0x16, 0x50, 0x6d,
	0x61, 0x47, 0x65, 0x74, 0x43, 0x6f, 0x6d, 0x70, 0x6f, 0x73, 0x65, 0x73, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x05, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x12, 0x2c, 0x0a, 0x05, 0x69, 0x74,
	0x65, 0x6d, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x2e, 0x50, 0x6d, 0x61, 0x43, 0x6f, 0x6d, 0x70, 0x6f, 0x73, 0x65, 0x73, 0x49, 0x6e, 0x66,
	0x6f, 0x52, 0x05, 0x69, 0x74, 0x65, 0x6d, 0x73, 0x22, 0x6b, 0x0a, 0x0f, 0x50, 0x6d, 0x61, 0x43,
	0x6f, 0x6d, 0x70, 0x6f, 0x73, 0x65, 0x73, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x12, 0x0a, 0x04, 0x6e,
	0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12,
	0x18, 0x0a, 0x07, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x07, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x12, 0x12, 0x0a, 0x04, 0x70, 0x6f, 0x72,
	0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x70, 0x6f, 0x72, 0x74, 0x12, 0x16, 0x0a,
	0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x73,
	0x74, 0x61, 0x74, 0x75, 0x73, 0x22, 0x60, 0x0a, 0x13, 0x50, 0x6d, 0x61, 0x4f, 0x70, 0x65, 0x72,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x17, 0x0a, 0x07,
	0x68, 0x6f, 0x73, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x06, 0x68,
	0x6f, 0x73, 0x74, 0x49, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x6f, 0x70, 0x65,
	0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x6f, 0x70,
	0x65, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x22, 0x54, 0x0a, 0x11, 0x50, 0x6d, 0x61, 0x53, 0x65,
	0x74, 0x50, 0x6f, 0x72, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x17, 0x0a, 0x07,
	0x68, 0x6f, 0x73, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x06, 0x68,
	0x6f, 0x73, 0x74, 0x49, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x70, 0x6f, 0x72,
	0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x70, 0x6f, 0x72, 0x74, 0x22, 0x74, 0x0a,
	0x14, 0x50, 0x6d, 0x61, 0x47, 0x65, 0x74, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x73, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x17, 0x0a, 0x07, 0x68, 0x6f, 0x73, 0x74, 0x5f, 0x69, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x06, 0x68, 0x6f, 0x73, 0x74, 0x49, 0x64, 0x12, 0x12,
	0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61,
	0x6d, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x70, 0x61, 0x67, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x04, 0x70, 0x61, 0x67, 0x65, 0x12, 0x1b, 0x0a, 0x09, 0x70, 0x61, 0x67, 0x65, 0x5f, 0x73,
	0x69, 0x7a, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x70, 0x61, 0x67, 0x65, 0x53,
	0x69, 0x7a, 0x65, 0x22, 0x59, 0x0a, 0x15, 0x50, 0x6d, 0x61, 0x47, 0x65, 0x74, 0x53, 0x65, 0x72,
	0x76, 0x65, 0x72, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x14, 0x0a, 0x05,
	0x74, 0x6f, 0x74, 0x61, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x74, 0x6f, 0x74,
	0x61, 0x6c, 0x12, 0x2a, 0x0a, 0x05, 0x69, 0x74, 0x65, 0x6d, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28,
	0x0b, 0x32, 0x14, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x50, 0x6d, 0x61, 0x53, 0x65, 0x72,
	0x76, 0x65, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x05, 0x69, 0x74, 0x65, 0x6d, 0x73, 0x22, 0x51,
	0x0a, 0x0d, 0x50, 0x6d, 0x61, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x12,
	0x18, 0x0a, 0x07, 0x76, 0x65, 0x72, 0x62, 0x6f, 0x73, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x07, 0x76, 0x65, 0x72, 0x62, 0x6f, 0x73, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x68, 0x6f, 0x73,
	0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x68, 0x6f, 0x73, 0x74, 0x12, 0x12, 0x0a,
	0x04, 0x70, 0x6f, 0x72, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x70, 0x6f, 0x72,
	0x74, 0x22, 0x84, 0x01, 0x0a, 0x13, 0x50, 0x6d, 0x61, 0x41, 0x64, 0x64, 0x53, 0x65, 0x72, 0x76,
	0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x17, 0x0a, 0x07, 0x68, 0x6f, 0x73,
	0x74, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x06, 0x68, 0x6f, 0x73, 0x74,
	0x49, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x76, 0x65, 0x72, 0x62, 0x6f, 0x73,
	0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x76, 0x65, 0x72, 0x62, 0x6f, 0x73, 0x65,
	0x12, 0x12, 0x0a, 0x04, 0x68, 0x6f, 0x73, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04,
	0x68, 0x6f, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x70, 0x6f, 0x72, 0x74, 0x18, 0x05, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x04, 0x70, 0x6f, 0x72, 0x74, 0x22, 0x6d, 0x0a, 0x16, 0x50, 0x6d, 0x61, 0x52,
	0x65, 0x6d, 0x6f, 0x76, 0x65, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x17, 0x0a, 0x07, 0x68, 0x6f, 0x73, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0d, 0x52, 0x06, 0x68, 0x6f, 0x73, 0x74, 0x49, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e,
	0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12,
	0x12, 0x0a, 0x04, 0x68, 0x6f, 0x73, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x68,
	0x6f, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x70, 0x6f, 0x72, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x04, 0x70, 0x6f, 0x72, 0x74, 0x32, 0x83, 0x04, 0x0a, 0x03, 0x50, 0x6d, 0x61, 0x12,
	0x4d, 0x0a, 0x0e, 0x50, 0x6d, 0x61, 0x47, 0x65, 0x74, 0x43, 0x6f, 0x6d, 0x70, 0x6f, 0x73, 0x65,
	0x73, 0x12, 0x1c, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x50, 0x6d, 0x61, 0x47, 0x65, 0x74,
	0x43, 0x6f, 0x6d, 0x70, 0x6f, 0x73, 0x65, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a,
	0x1d, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x50, 0x6d, 0x61, 0x47, 0x65, 0x74, 0x43, 0x6f,
	0x6d, 0x70, 0x6f, 0x73, 0x65, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x44,
	0x0a, 0x0c, 0x50, 0x6d, 0x61, 0x4f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x1a,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x50, 0x6d, 0x61, 0x4f, 0x70, 0x65, 0x72, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x18, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x2e, 0x50, 0x6d, 0x61, 0x43, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x40, 0x0a, 0x0a, 0x50, 0x6d, 0x61, 0x53, 0x65, 0x74, 0x50, 0x6f,
	0x72, 0x74, 0x12, 0x18, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x50, 0x6d, 0x61, 0x53, 0x65,
	0x74, 0x50, 0x6f, 0x72, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x18, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x50, 0x6d, 0x61, 0x43, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x4a, 0x0a, 0x0d, 0x50, 0x6d, 0x61, 0x47, 0x65, 0x74,
	0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x73, 0x12, 0x1b, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e,
	0x50, 0x6d, 0x61, 0x47, 0x65, 0x74, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x73, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x1a, 0x1c, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x50, 0x6d, 0x61,
	0x47, 0x65, 0x74, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x44, 0x0a, 0x0c, 0x50, 0x6d, 0x61, 0x41, 0x64, 0x64, 0x53, 0x65, 0x72, 0x76,
	0x65, 0x72, 0x12, 0x1a, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x50, 0x6d, 0x61, 0x41, 0x64,
	0x64, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x18,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x50, 0x6d, 0x61, 0x43, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x47, 0x0a, 0x0f, 0x50, 0x6d, 0x61, 0x55,
	0x70, 0x64, 0x61, 0x74, 0x65, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x12, 0x1a, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x2e, 0x50, 0x6d, 0x61, 0x41, 0x64, 0x64, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x18, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e,
	0x50, 0x6d, 0x61, 0x43, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x4a, 0x0a, 0x0f, 0x50, 0x6d, 0x61, 0x52, 0x65, 0x6d, 0x6f, 0x76, 0x65, 0x53, 0x65,
	0x72, 0x76, 0x65, 0x72, 0x12, 0x1d, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x50, 0x6d, 0x61,
	0x52, 0x65, 0x6d, 0x6f, 0x76, 0x65, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x1a, 0x18, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x50, 0x6d, 0x61, 0x43,
	0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x0a, 0x5a,
	0x08, 0x2e, 0x2e, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x33,
}

var (
	file_pma_proto_rawDescOnce sync.Once
	file_pma_proto_rawDescData = file_pma_proto_rawDesc
)

func file_pma_proto_rawDescGZIP() []byte {
	file_pma_proto_rawDescOnce.Do(func() {
		file_pma_proto_rawDescData = protoimpl.X.CompressGZIP(file_pma_proto_rawDescData)
	})
	return file_pma_proto_rawDescData
}

var file_pma_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_pma_proto_goTypes = []interface{}{
	(*PmaCommonResponse)(nil),      // 0: proto.PmaCommonResponse
	(*PmaGetComposesRequest)(nil),  // 1: proto.PmaGetComposesRequest
	(*PmaGetComposesResponse)(nil), // 2: proto.PmaGetComposesResponse
	(*PmaComposesInfo)(nil),        // 3: proto.PmaComposesInfo
	(*PmaOperationRequest)(nil),    // 4: proto.PmaOperationRequest
	(*PmaSetPortRequest)(nil),      // 5: proto.PmaSetPortRequest
	(*PmaGetServersRequest)(nil),   // 6: proto.PmaGetServersRequest
	(*PmaGetServersResponse)(nil),  // 7: proto.PmaGetServersResponse
	(*PmaServerInfo)(nil),          // 8: proto.PmaServerInfo
	(*PmaAddServerRequest)(nil),    // 9: proto.PmaAddServerRequest
	(*PmaRemoveServerRequest)(nil), // 10: proto.PmaRemoveServerRequest
}
var file_pma_proto_depIdxs = []int32{
	3,  // 0: proto.PmaGetComposesResponse.items:type_name -> proto.PmaComposesInfo
	8,  // 1: proto.PmaGetServersResponse.items:type_name -> proto.PmaServerInfo
	1,  // 2: proto.Pma.PmaGetComposes:input_type -> proto.PmaGetComposesRequest
	4,  // 3: proto.Pma.PmaOperation:input_type -> proto.PmaOperationRequest
	5,  // 4: proto.Pma.PmaSetPort:input_type -> proto.PmaSetPortRequest
	6,  // 5: proto.Pma.PmaGetServers:input_type -> proto.PmaGetServersRequest
	9,  // 6: proto.Pma.PmaAddServer:input_type -> proto.PmaAddServerRequest
	9,  // 7: proto.Pma.PmaUpdateServer:input_type -> proto.PmaAddServerRequest
	10, // 8: proto.Pma.PmaRemoveServer:input_type -> proto.PmaRemoveServerRequest
	2,  // 9: proto.Pma.PmaGetComposes:output_type -> proto.PmaGetComposesResponse
	0,  // 10: proto.Pma.PmaOperation:output_type -> proto.PmaCommonResponse
	0,  // 11: proto.Pma.PmaSetPort:output_type -> proto.PmaCommonResponse
	7,  // 12: proto.Pma.PmaGetServers:output_type -> proto.PmaGetServersResponse
	0,  // 13: proto.Pma.PmaAddServer:output_type -> proto.PmaCommonResponse
	0,  // 14: proto.Pma.PmaUpdateServer:output_type -> proto.PmaCommonResponse
	0,  // 15: proto.Pma.PmaRemoveServer:output_type -> proto.PmaCommonResponse
	9,  // [9:16] is the sub-list for method output_type
	2,  // [2:9] is the sub-list for method input_type
	2,  // [2:2] is the sub-list for extension type_name
	2,  // [2:2] is the sub-list for extension extendee
	0,  // [0:2] is the sub-list for field type_name
}

func init() { file_pma_proto_init() }
func file_pma_proto_init() {
	if File_pma_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_pma_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PmaCommonResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pma_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PmaGetComposesRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pma_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PmaGetComposesResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pma_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PmaComposesInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pma_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PmaOperationRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pma_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PmaSetPortRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pma_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PmaGetServersRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pma_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PmaGetServersResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pma_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PmaServerInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pma_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PmaAddServerRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pma_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PmaRemoveServerRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_pma_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pma_proto_goTypes,
		DependencyIndexes: file_pma_proto_depIdxs,
		MessageInfos:      file_pma_proto_msgTypes,
	}.Build()
	File_pma_proto = out.File
	file_pma_proto_rawDesc = nil
	file_pma_proto_goTypes = nil
	file_pma_proto_depIdxs = nil
}
