// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v6.31.1
// source: pma.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	Pma_PmaGetComposes_FullMethodName  = "/proto.Pma/PmaGetComposes"
	Pma_PmaOperation_FullMethodName    = "/proto.Pma/PmaOperation"
	Pma_PmaSetPort_FullMethodName      = "/proto.Pma/PmaSetPort"
	Pma_PmaGetServers_FullMethodName   = "/proto.Pma/PmaGetServers"
	Pma_PmaAddServer_FullMethodName    = "/proto.Pma/PmaAddServer"
	Pma_PmaUpdateServer_FullMethodName = "/proto.Pma/PmaUpdateServer"
	Pma_PmaRemoveServer_FullMethodName = "/proto.Pma/PmaRemoveServer"
)

// PmaClient is the client API for Pma service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type PmaClient interface {
	PmaGetComposes(ctx context.Context, in *PmaGetComposesRequest, opts ...grpc.CallOption) (*PmaGetComposesResponse, error)
	PmaOperation(ctx context.Context, in *PmaOperationRequest, opts ...grpc.CallOption) (*PmaCommonResponse, error)
	PmaSetPort(ctx context.Context, in *PmaSetPortRequest, opts ...grpc.CallOption) (*PmaCommonResponse, error)
	PmaGetServers(ctx context.Context, in *PmaGetServersRequest, opts ...grpc.CallOption) (*PmaGetServersResponse, error)
	PmaAddServer(ctx context.Context, in *PmaAddServerRequest, opts ...grpc.CallOption) (*PmaCommonResponse, error)
	PmaUpdateServer(ctx context.Context, in *PmaAddServerRequest, opts ...grpc.CallOption) (*PmaCommonResponse, error)
	PmaRemoveServer(ctx context.Context, in *PmaRemoveServerRequest, opts ...grpc.CallOption) (*PmaCommonResponse, error)
}

type pmaClient struct {
	cc grpc.ClientConnInterface
}

func NewPmaClient(cc grpc.ClientConnInterface) PmaClient {
	return &pmaClient{cc}
}

func (c *pmaClient) PmaGetComposes(ctx context.Context, in *PmaGetComposesRequest, opts ...grpc.CallOption) (*PmaGetComposesResponse, error) {
	out := new(PmaGetComposesResponse)
	err := c.cc.Invoke(ctx, Pma_PmaGetComposes_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pmaClient) PmaOperation(ctx context.Context, in *PmaOperationRequest, opts ...grpc.CallOption) (*PmaCommonResponse, error) {
	out := new(PmaCommonResponse)
	err := c.cc.Invoke(ctx, Pma_PmaOperation_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pmaClient) PmaSetPort(ctx context.Context, in *PmaSetPortRequest, opts ...grpc.CallOption) (*PmaCommonResponse, error) {
	out := new(PmaCommonResponse)
	err := c.cc.Invoke(ctx, Pma_PmaSetPort_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pmaClient) PmaGetServers(ctx context.Context, in *PmaGetServersRequest, opts ...grpc.CallOption) (*PmaGetServersResponse, error) {
	out := new(PmaGetServersResponse)
	err := c.cc.Invoke(ctx, Pma_PmaGetServers_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pmaClient) PmaAddServer(ctx context.Context, in *PmaAddServerRequest, opts ...grpc.CallOption) (*PmaCommonResponse, error) {
	out := new(PmaCommonResponse)
	err := c.cc.Invoke(ctx, Pma_PmaAddServer_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pmaClient) PmaUpdateServer(ctx context.Context, in *PmaAddServerRequest, opts ...grpc.CallOption) (*PmaCommonResponse, error) {
	out := new(PmaCommonResponse)
	err := c.cc.Invoke(ctx, Pma_PmaUpdateServer_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pmaClient) PmaRemoveServer(ctx context.Context, in *PmaRemoveServerRequest, opts ...grpc.CallOption) (*PmaCommonResponse, error) {
	out := new(PmaCommonResponse)
	err := c.cc.Invoke(ctx, Pma_PmaRemoveServer_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PmaServer is the server API for Pma service.
// All implementations must embed UnimplementedPmaServer
// for forward compatibility
type PmaServer interface {
	PmaGetComposes(context.Context, *PmaGetComposesRequest) (*PmaGetComposesResponse, error)
	PmaOperation(context.Context, *PmaOperationRequest) (*PmaCommonResponse, error)
	PmaSetPort(context.Context, *PmaSetPortRequest) (*PmaCommonResponse, error)
	PmaGetServers(context.Context, *PmaGetServersRequest) (*PmaGetServersResponse, error)
	PmaAddServer(context.Context, *PmaAddServerRequest) (*PmaCommonResponse, error)
	PmaUpdateServer(context.Context, *PmaAddServerRequest) (*PmaCommonResponse, error)
	PmaRemoveServer(context.Context, *PmaRemoveServerRequest) (*PmaCommonResponse, error)
	mustEmbedUnimplementedPmaServer()
}

// UnimplementedPmaServer must be embedded to have forward compatible implementations.
type UnimplementedPmaServer struct {
}

func (UnimplementedPmaServer) PmaGetComposes(context.Context, *PmaGetComposesRequest) (*PmaGetComposesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PmaGetComposes not implemented")
}
func (UnimplementedPmaServer) PmaOperation(context.Context, *PmaOperationRequest) (*PmaCommonResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PmaOperation not implemented")
}
func (UnimplementedPmaServer) PmaSetPort(context.Context, *PmaSetPortRequest) (*PmaCommonResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PmaSetPort not implemented")
}
func (UnimplementedPmaServer) PmaGetServers(context.Context, *PmaGetServersRequest) (*PmaGetServersResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PmaGetServers not implemented")
}
func (UnimplementedPmaServer) PmaAddServer(context.Context, *PmaAddServerRequest) (*PmaCommonResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PmaAddServer not implemented")
}
func (UnimplementedPmaServer) PmaUpdateServer(context.Context, *PmaAddServerRequest) (*PmaCommonResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PmaUpdateServer not implemented")
}
func (UnimplementedPmaServer) PmaRemoveServer(context.Context, *PmaRemoveServerRequest) (*PmaCommonResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PmaRemoveServer not implemented")
}
func (UnimplementedPmaServer) mustEmbedUnimplementedPmaServer() {}

// UnsafePmaServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PmaServer will
// result in compilation errors.
type UnsafePmaServer interface {
	mustEmbedUnimplementedPmaServer()
}

func RegisterPmaServer(s grpc.ServiceRegistrar, srv PmaServer) {
	s.RegisterService(&Pma_ServiceDesc, srv)
}

func _Pma_PmaGetComposes_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PmaGetComposesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PmaServer).PmaGetComposes(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Pma_PmaGetComposes_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PmaServer).PmaGetComposes(ctx, req.(*PmaGetComposesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Pma_PmaOperation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PmaOperationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PmaServer).PmaOperation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Pma_PmaOperation_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PmaServer).PmaOperation(ctx, req.(*PmaOperationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Pma_PmaSetPort_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PmaSetPortRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PmaServer).PmaSetPort(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Pma_PmaSetPort_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PmaServer).PmaSetPort(ctx, req.(*PmaSetPortRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Pma_PmaGetServers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PmaGetServersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PmaServer).PmaGetServers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Pma_PmaGetServers_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PmaServer).PmaGetServers(ctx, req.(*PmaGetServersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Pma_PmaAddServer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PmaAddServerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PmaServer).PmaAddServer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Pma_PmaAddServer_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PmaServer).PmaAddServer(ctx, req.(*PmaAddServerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Pma_PmaUpdateServer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PmaAddServerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PmaServer).PmaUpdateServer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Pma_PmaUpdateServer_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PmaServer).PmaUpdateServer(ctx, req.(*PmaAddServerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Pma_PmaRemoveServer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PmaRemoveServerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PmaServer).PmaRemoveServer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Pma_PmaRemoveServer_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PmaServer).PmaRemoveServer(ctx, req.(*PmaRemoveServerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Pma_ServiceDesc is the grpc.ServiceDesc for Pma service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Pma_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "proto.Pma",
	HandlerType: (*PmaServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "PmaGetComposes",
			Handler:    _Pma_PmaGetComposes_Handler,
		},
		{
			MethodName: "PmaOperation",
			Handler:    _Pma_PmaOperation_Handler,
		},
		{
			MethodName: "PmaSetPort",
			Handler:    _Pma_PmaSetPort_Handler,
		},
		{
			MethodName: "PmaGetServers",
			Handler:    _Pma_PmaGetServers_Handler,
		},
		{
			MethodName: "PmaAddServer",
			Handler:    _Pma_PmaAddServer_Handler,
		},
		{
			MethodName: "PmaUpdateServer",
			Handler:    _Pma_PmaUpdateServer_Handler,
		},
		{
			MethodName: "PmaRemoveServer",
			Handler:    _Pma_PmaRemoveServer_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pma.proto",
}
