// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.33.0
// 	protoc        v6.31.1
// source: postgresql.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PGCommonResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Success bool   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error   string `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
}

func (x *PGCommonResponse) Reset() {
	*x = PGCommonResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_postgresql_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PGCommonResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PGCommonResponse) ProtoMessage() {}

func (x *PGCommonResponse) ProtoReflect() protoreflect.Message {
	mi := &file_postgresql_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PGCommonResponse.ProtoReflect.Descriptor instead.
func (*PGCommonResponse) Descriptor() ([]byte, []int) {
	return file_postgresql_proto_rawDescGZIP(), []int{0}
}

func (x *PGCommonResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *PGCommonResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type PGGetComposesRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	HostId   uint32 `protobuf:"varint,1,opt,name=host_id,json=hostId,proto3" json:"host_id,omitempty"`
	Page     int32  `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`
	PageSize int32  `protobuf:"varint,3,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
}

func (x *PGGetComposesRequest) Reset() {
	*x = PGGetComposesRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_postgresql_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PGGetComposesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PGGetComposesRequest) ProtoMessage() {}

func (x *PGGetComposesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_postgresql_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PGGetComposesRequest.ProtoReflect.Descriptor instead.
func (*PGGetComposesRequest) Descriptor() ([]byte, []int) {
	return file_postgresql_proto_rawDescGZIP(), []int{1}
}

func (x *PGGetComposesRequest) GetHostId() uint32 {
	if x != nil {
		return x.HostId
	}
	return 0
}

func (x *PGGetComposesRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *PGGetComposesRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type PGGetComposesResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Total int64             `protobuf:"varint,1,opt,name=total,proto3" json:"total,omitempty"`
	Items []*PGComposesInfo `protobuf:"bytes,2,rep,name=items,proto3" json:"items,omitempty"`
}

func (x *PGGetComposesResponse) Reset() {
	*x = PGGetComposesResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_postgresql_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PGGetComposesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PGGetComposesResponse) ProtoMessage() {}

func (x *PGGetComposesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_postgresql_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PGGetComposesResponse.ProtoReflect.Descriptor instead.
func (*PGGetComposesResponse) Descriptor() ([]byte, []int) {
	return file_postgresql_proto_rawDescGZIP(), []int{2}
}

func (x *PGGetComposesResponse) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *PGGetComposesResponse) GetItems() []*PGComposesInfo {
	if x != nil {
		return x.Items
	}
	return nil
}

type PGComposesInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name    string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Version string `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	Port    string `protobuf:"bytes,3,opt,name=port,proto3" json:"port,omitempty"`
	Status  string `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"`
}

func (x *PGComposesInfo) Reset() {
	*x = PGComposesInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_postgresql_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PGComposesInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PGComposesInfo) ProtoMessage() {}

func (x *PGComposesInfo) ProtoReflect() protoreflect.Message {
	mi := &file_postgresql_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PGComposesInfo.ProtoReflect.Descriptor instead.
func (*PGComposesInfo) Descriptor() ([]byte, []int) {
	return file_postgresql_proto_rawDescGZIP(), []int{3}
}

func (x *PGComposesInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *PGComposesInfo) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *PGComposesInfo) GetPort() string {
	if x != nil {
		return x.Port
	}
	return ""
}

func (x *PGComposesInfo) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type PGOperationRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	HostId    uint32 `protobuf:"varint,1,opt,name=host_id,json=hostId,proto3" json:"host_id,omitempty"`
	Name      string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Operation string `protobuf:"bytes,3,opt,name=operation,proto3" json:"operation,omitempty"`
}

func (x *PGOperationRequest) Reset() {
	*x = PGOperationRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_postgresql_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PGOperationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PGOperationRequest) ProtoMessage() {}

func (x *PGOperationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_postgresql_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PGOperationRequest.ProtoReflect.Descriptor instead.
func (*PGOperationRequest) Descriptor() ([]byte, []int) {
	return file_postgresql_proto_rawDescGZIP(), []int{4}
}

func (x *PGOperationRequest) GetHostId() uint32 {
	if x != nil {
		return x.HostId
	}
	return 0
}

func (x *PGOperationRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *PGOperationRequest) GetOperation() string {
	if x != nil {
		return x.Operation
	}
	return ""
}

type PGSetPortRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	HostId uint32 `protobuf:"varint,1,opt,name=host_id,json=hostId,proto3" json:"host_id,omitempty"`
	Name   string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Port   string `protobuf:"bytes,3,opt,name=port,proto3" json:"port,omitempty"`
}

func (x *PGSetPortRequest) Reset() {
	*x = PGSetPortRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_postgresql_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PGSetPortRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PGSetPortRequest) ProtoMessage() {}

func (x *PGSetPortRequest) ProtoReflect() protoreflect.Message {
	mi := &file_postgresql_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PGSetPortRequest.ProtoReflect.Descriptor instead.
func (*PGSetPortRequest) Descriptor() ([]byte, []int) {
	return file_postgresql_proto_rawDescGZIP(), []int{5}
}

func (x *PGSetPortRequest) GetHostId() uint32 {
	if x != nil {
		return x.HostId
	}
	return 0
}

func (x *PGSetPortRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *PGSetPortRequest) GetPort() string {
	if x != nil {
		return x.Port
	}
	return ""
}

type PGGetConfRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	HostId uint32 `protobuf:"varint,1,opt,name=host_id,json=hostId,proto3" json:"host_id,omitempty"`
	Name   string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *PGGetConfRequest) Reset() {
	*x = PGGetConfRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_postgresql_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PGGetConfRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PGGetConfRequest) ProtoMessage() {}

func (x *PGGetConfRequest) ProtoReflect() protoreflect.Message {
	mi := &file_postgresql_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PGGetConfRequest.ProtoReflect.Descriptor instead.
func (*PGGetConfRequest) Descriptor() ([]byte, []int) {
	return file_postgresql_proto_rawDescGZIP(), []int{6}
}

func (x *PGGetConfRequest) GetHostId() uint32 {
	if x != nil {
		return x.HostId
	}
	return 0
}

func (x *PGGetConfRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type PGGetConfResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Content string `protobuf:"bytes,1,opt,name=content,proto3" json:"content,omitempty"`
}

func (x *PGGetConfResponse) Reset() {
	*x = PGGetConfResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_postgresql_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PGGetConfResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PGGetConfResponse) ProtoMessage() {}

func (x *PGGetConfResponse) ProtoReflect() protoreflect.Message {
	mi := &file_postgresql_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PGGetConfResponse.ProtoReflect.Descriptor instead.
func (*PGGetConfResponse) Descriptor() ([]byte, []int) {
	return file_postgresql_proto_rawDescGZIP(), []int{7}
}

func (x *PGGetConfResponse) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

type PGSetConfRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	HostId  uint32 `protobuf:"varint,1,opt,name=host_id,json=hostId,proto3" json:"host_id,omitempty"`
	Name    string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Content string `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`
}

func (x *PGSetConfRequest) Reset() {
	*x = PGSetConfRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_postgresql_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PGSetConfRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PGSetConfRequest) ProtoMessage() {}

func (x *PGSetConfRequest) ProtoReflect() protoreflect.Message {
	mi := &file_postgresql_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PGSetConfRequest.ProtoReflect.Descriptor instead.
func (*PGSetConfRequest) Descriptor() ([]byte, []int) {
	return file_postgresql_proto_rawDescGZIP(), []int{8}
}

func (x *PGSetConfRequest) GetHostId() uint32 {
	if x != nil {
		return x.HostId
	}
	return 0
}

func (x *PGSetConfRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *PGSetConfRequest) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

var File_postgresql_proto protoreflect.FileDescriptor

var file_postgresql_proto_rawDesc = []byte{
	0x0a, 0x10, 0x70, 0x6f, 0x73, 0x74, 0x67, 0x72, 0x65, 0x73, 0x71, 0x6c, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x12, 0x05, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x42, 0x0a, 0x10, 0x50, 0x47, 0x43,
	0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x18, 0x0a,
	0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07,
	0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x12, 0x14, 0x0a, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x22, 0x60, 0x0a,
	0x14, 0x50, 0x47, 0x47, 0x65, 0x74, 0x43, 0x6f, 0x6d, 0x70, 0x6f, 0x73, 0x65, 0x73, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x17, 0x0a, 0x07, 0x68, 0x6f, 0x73, 0x74, 0x5f, 0x69, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x06, 0x68, 0x6f, 0x73, 0x74, 0x49, 0x64, 0x12, 0x12,
	0x0a, 0x04, 0x70, 0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x70, 0x61,
	0x67, 0x65, 0x12, 0x1b, 0x0a, 0x09, 0x70, 0x61, 0x67, 0x65, 0x5f, 0x73, 0x69, 0x7a, 0x65, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x70, 0x61, 0x67, 0x65, 0x53, 0x69, 0x7a, 0x65, 0x22,
	0x5a, 0x0a, 0x15, 0x50, 0x47, 0x47, 0x65, 0x74, 0x43, 0x6f, 0x6d, 0x70, 0x6f, 0x73, 0x65, 0x73,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x6f, 0x74, 0x61,
	0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x12, 0x2b,
	0x0a, 0x05, 0x69, 0x74, 0x65, 0x6d, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x15, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x50, 0x47, 0x43, 0x6f, 0x6d, 0x70, 0x6f, 0x73, 0x65, 0x73,
	0x49, 0x6e, 0x66, 0x6f, 0x52, 0x05, 0x69, 0x74, 0x65, 0x6d, 0x73, 0x22, 0x6a, 0x0a, 0x0e, 0x50,
	0x47, 0x43, 0x6f, 0x6d, 0x70, 0x6f, 0x73, 0x65, 0x73, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x12, 0x0a,
	0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d,
	0x65, 0x12, 0x18, 0x0a, 0x07, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x07, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x12, 0x12, 0x0a, 0x04, 0x70,
	0x6f, 0x72, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x70, 0x6f, 0x72, 0x74, 0x12,
	0x16, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x22, 0x5f, 0x0a, 0x12, 0x50, 0x47, 0x4f, 0x70, 0x65,
	0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x17, 0x0a,
	0x07, 0x68, 0x6f, 0x73, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x06,
	0x68, 0x6f, 0x73, 0x74, 0x49, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x6f, 0x70,
	0x65, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x6f,
	0x70, 0x65, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x22, 0x53, 0x0a, 0x10, 0x50, 0x47, 0x53, 0x65,
	0x74, 0x50, 0x6f, 0x72, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x17, 0x0a, 0x07,
	0x68, 0x6f, 0x73, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x06, 0x68,
	0x6f, 0x73, 0x74, 0x49, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x70, 0x6f, 0x72,
	0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x70, 0x6f, 0x72, 0x74, 0x22, 0x3f, 0x0a,
	0x10, 0x50, 0x47, 0x47, 0x65, 0x74, 0x43, 0x6f, 0x6e, 0x66, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x17, 0x0a, 0x07, 0x68, 0x6f, 0x73, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0d, 0x52, 0x06, 0x68, 0x6f, 0x73, 0x74, 0x49, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61,
	0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x22, 0x2d,
	0x0a, 0x11, 0x50, 0x47, 0x47, 0x65, 0x74, 0x43, 0x6f, 0x6e, 0x66, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x22, 0x59, 0x0a,
	0x10, 0x50, 0x47, 0x53, 0x65, 0x74, 0x43, 0x6f, 0x6e, 0x66, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x17, 0x0a, 0x07, 0x68, 0x6f, 0x73, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0d, 0x52, 0x06, 0x68, 0x6f, 0x73, 0x74, 0x49, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61,
	0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x18,
	0x0a, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x32, 0xd9, 0x02, 0x0a, 0x0a, 0x50, 0x6f, 0x73,
	0x74, 0x67, 0x72, 0x65, 0x53, 0x71, 0x6c, 0x12, 0x4a, 0x0a, 0x0d, 0x50, 0x47, 0x47, 0x65, 0x74,
	0x43, 0x6f, 0x6d, 0x70, 0x6f, 0x73, 0x65, 0x73, 0x12, 0x1b, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x2e, 0x50, 0x47, 0x47, 0x65, 0x74, 0x43, 0x6f, 0x6d, 0x70, 0x6f, 0x73, 0x65, 0x73, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1c, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x50, 0x47,
	0x47, 0x65, 0x74, 0x43, 0x6f, 0x6d, 0x70, 0x6f, 0x73, 0x65, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x41, 0x0a, 0x0b, 0x50, 0x47, 0x4f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x12, 0x19, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x50, 0x47, 0x4f, 0x70, 0x65,
	0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x17, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x50, 0x47, 0x43, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x3d, 0x0a, 0x09, 0x50, 0x47, 0x53, 0x65, 0x74, 0x50,
	0x6f, 0x72, 0x74, 0x12, 0x17, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x50, 0x47, 0x53, 0x65,
	0x74, 0x50, 0x6f, 0x72, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x17, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x50, 0x47, 0x43, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x3e, 0x0a, 0x09, 0x50, 0x47, 0x47, 0x65, 0x74, 0x43, 0x6f,
	0x6e, 0x66, 0x12, 0x17, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x50, 0x47, 0x47, 0x65, 0x74,
	0x43, 0x6f, 0x6e, 0x66, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x18, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x2e, 0x50, 0x47, 0x47, 0x65, 0x74, 0x43, 0x6f, 0x6e, 0x66, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x3d, 0x0a, 0x09, 0x50, 0x47, 0x53, 0x65, 0x74, 0x43, 0x6f,
	0x6e, 0x66, 0x12, 0x17, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x50, 0x47, 0x53, 0x65, 0x74,
	0x43, 0x6f, 0x6e, 0x66, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x17, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x2e, 0x50, 0x47, 0x43, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x42, 0x0a, 0x5a, 0x08, 0x2e, 0x2e, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_postgresql_proto_rawDescOnce sync.Once
	file_postgresql_proto_rawDescData = file_postgresql_proto_rawDesc
)

func file_postgresql_proto_rawDescGZIP() []byte {
	file_postgresql_proto_rawDescOnce.Do(func() {
		file_postgresql_proto_rawDescData = protoimpl.X.CompressGZIP(file_postgresql_proto_rawDescData)
	})
	return file_postgresql_proto_rawDescData
}

var file_postgresql_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_postgresql_proto_goTypes = []interface{}{
	(*PGCommonResponse)(nil),      // 0: proto.PGCommonResponse
	(*PGGetComposesRequest)(nil),  // 1: proto.PGGetComposesRequest
	(*PGGetComposesResponse)(nil), // 2: proto.PGGetComposesResponse
	(*PGComposesInfo)(nil),        // 3: proto.PGComposesInfo
	(*PGOperationRequest)(nil),    // 4: proto.PGOperationRequest
	(*PGSetPortRequest)(nil),      // 5: proto.PGSetPortRequest
	(*PGGetConfRequest)(nil),      // 6: proto.PGGetConfRequest
	(*PGGetConfResponse)(nil),     // 7: proto.PGGetConfResponse
	(*PGSetConfRequest)(nil),      // 8: proto.PGSetConfRequest
}
var file_postgresql_proto_depIdxs = []int32{
	3, // 0: proto.PGGetComposesResponse.items:type_name -> proto.PGComposesInfo
	1, // 1: proto.PostgreSql.PGGetComposes:input_type -> proto.PGGetComposesRequest
	4, // 2: proto.PostgreSql.PGOperation:input_type -> proto.PGOperationRequest
	5, // 3: proto.PostgreSql.PGSetPort:input_type -> proto.PGSetPortRequest
	6, // 4: proto.PostgreSql.PGGetConf:input_type -> proto.PGGetConfRequest
	8, // 5: proto.PostgreSql.PGSetConf:input_type -> proto.PGSetConfRequest
	2, // 6: proto.PostgreSql.PGGetComposes:output_type -> proto.PGGetComposesResponse
	0, // 7: proto.PostgreSql.PGOperation:output_type -> proto.PGCommonResponse
	0, // 8: proto.PostgreSql.PGSetPort:output_type -> proto.PGCommonResponse
	7, // 9: proto.PostgreSql.PGGetConf:output_type -> proto.PGGetConfResponse
	0, // 10: proto.PostgreSql.PGSetConf:output_type -> proto.PGCommonResponse
	6, // [6:11] is the sub-list for method output_type
	1, // [1:6] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_postgresql_proto_init() }
func file_postgresql_proto_init() {
	if File_postgresql_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_postgresql_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PGCommonResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_postgresql_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PGGetComposesRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_postgresql_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PGGetComposesResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_postgresql_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PGComposesInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_postgresql_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PGOperationRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_postgresql_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PGSetPortRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_postgresql_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PGGetConfRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_postgresql_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PGGetConfResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_postgresql_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PGSetConfRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_postgresql_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_postgresql_proto_goTypes,
		DependencyIndexes: file_postgresql_proto_depIdxs,
		MessageInfos:      file_postgresql_proto_msgTypes,
	}.Build()
	File_postgresql_proto = out.File
	file_postgresql_proto_rawDesc = nil
	file_postgresql_proto_goTypes = nil
	file_postgresql_proto_depIdxs = nil
}
