// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v6.31.1
// source: postgresql.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	PostgreSql_PGGetComposes_FullMethodName = "/proto.PostgreSql/PGGetComposes"
	PostgreSql_PGOperation_FullMethodName   = "/proto.PostgreSql/PGOperation"
	PostgreSql_PGSetPort_FullMethodName     = "/proto.PostgreSql/PGSetPort"
	PostgreSql_PGGetConf_FullMethodName     = "/proto.PostgreSql/PGGetConf"
	PostgreSql_PGSetConf_FullMethodName     = "/proto.PostgreSql/PGSetConf"
)

// PostgreSqlClient is the client API for PostgreSql service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type PostgreSqlClient interface {
	PGGetComposes(ctx context.Context, in *PGGetComposesRequest, opts ...grpc.CallOption) (*PGGetComposesResponse, error)
	PGOperation(ctx context.Context, in *PGOperationRequest, opts ...grpc.CallOption) (*PGCommonResponse, error)
	PGSetPort(ctx context.Context, in *PGSetPortRequest, opts ...grpc.CallOption) (*PGCommonResponse, error)
	PGGetConf(ctx context.Context, in *PGGetConfRequest, opts ...grpc.CallOption) (*PGGetConfResponse, error)
	PGSetConf(ctx context.Context, in *PGSetConfRequest, opts ...grpc.CallOption) (*PGCommonResponse, error)
}

type postgreSqlClient struct {
	cc grpc.ClientConnInterface
}

func NewPostgreSqlClient(cc grpc.ClientConnInterface) PostgreSqlClient {
	return &postgreSqlClient{cc}
}

func (c *postgreSqlClient) PGGetComposes(ctx context.Context, in *PGGetComposesRequest, opts ...grpc.CallOption) (*PGGetComposesResponse, error) {
	out := new(PGGetComposesResponse)
	err := c.cc.Invoke(ctx, PostgreSql_PGGetComposes_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *postgreSqlClient) PGOperation(ctx context.Context, in *PGOperationRequest, opts ...grpc.CallOption) (*PGCommonResponse, error) {
	out := new(PGCommonResponse)
	err := c.cc.Invoke(ctx, PostgreSql_PGOperation_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *postgreSqlClient) PGSetPort(ctx context.Context, in *PGSetPortRequest, opts ...grpc.CallOption) (*PGCommonResponse, error) {
	out := new(PGCommonResponse)
	err := c.cc.Invoke(ctx, PostgreSql_PGSetPort_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *postgreSqlClient) PGGetConf(ctx context.Context, in *PGGetConfRequest, opts ...grpc.CallOption) (*PGGetConfResponse, error) {
	out := new(PGGetConfResponse)
	err := c.cc.Invoke(ctx, PostgreSql_PGGetConf_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *postgreSqlClient) PGSetConf(ctx context.Context, in *PGSetConfRequest, opts ...grpc.CallOption) (*PGCommonResponse, error) {
	out := new(PGCommonResponse)
	err := c.cc.Invoke(ctx, PostgreSql_PGSetConf_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PostgreSqlServer is the server API for PostgreSql service.
// All implementations must embed UnimplementedPostgreSqlServer
// for forward compatibility
type PostgreSqlServer interface {
	PGGetComposes(context.Context, *PGGetComposesRequest) (*PGGetComposesResponse, error)
	PGOperation(context.Context, *PGOperationRequest) (*PGCommonResponse, error)
	PGSetPort(context.Context, *PGSetPortRequest) (*PGCommonResponse, error)
	PGGetConf(context.Context, *PGGetConfRequest) (*PGGetConfResponse, error)
	PGSetConf(context.Context, *PGSetConfRequest) (*PGCommonResponse, error)
	mustEmbedUnimplementedPostgreSqlServer()
}

// UnimplementedPostgreSqlServer must be embedded to have forward compatible implementations.
type UnimplementedPostgreSqlServer struct {
}

func (UnimplementedPostgreSqlServer) PGGetComposes(context.Context, *PGGetComposesRequest) (*PGGetComposesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PGGetComposes not implemented")
}
func (UnimplementedPostgreSqlServer) PGOperation(context.Context, *PGOperationRequest) (*PGCommonResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PGOperation not implemented")
}
func (UnimplementedPostgreSqlServer) PGSetPort(context.Context, *PGSetPortRequest) (*PGCommonResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PGSetPort not implemented")
}
func (UnimplementedPostgreSqlServer) PGGetConf(context.Context, *PGGetConfRequest) (*PGGetConfResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PGGetConf not implemented")
}
func (UnimplementedPostgreSqlServer) PGSetConf(context.Context, *PGSetConfRequest) (*PGCommonResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PGSetConf not implemented")
}
func (UnimplementedPostgreSqlServer) mustEmbedUnimplementedPostgreSqlServer() {}

// UnsafePostgreSqlServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PostgreSqlServer will
// result in compilation errors.
type UnsafePostgreSqlServer interface {
	mustEmbedUnimplementedPostgreSqlServer()
}

func RegisterPostgreSqlServer(s grpc.ServiceRegistrar, srv PostgreSqlServer) {
	s.RegisterService(&PostgreSql_ServiceDesc, srv)
}

func _PostgreSql_PGGetComposes_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PGGetComposesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PostgreSqlServer).PGGetComposes(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PostgreSql_PGGetComposes_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PostgreSqlServer).PGGetComposes(ctx, req.(*PGGetComposesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PostgreSql_PGOperation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PGOperationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PostgreSqlServer).PGOperation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PostgreSql_PGOperation_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PostgreSqlServer).PGOperation(ctx, req.(*PGOperationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PostgreSql_PGSetPort_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PGSetPortRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PostgreSqlServer).PGSetPort(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PostgreSql_PGSetPort_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PostgreSqlServer).PGSetPort(ctx, req.(*PGSetPortRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PostgreSql_PGGetConf_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PGGetConfRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PostgreSqlServer).PGGetConf(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PostgreSql_PGGetConf_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PostgreSqlServer).PGGetConf(ctx, req.(*PGGetConfRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PostgreSql_PGSetConf_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PGSetConfRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PostgreSqlServer).PGSetConf(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PostgreSql_PGSetConf_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PostgreSqlServer).PGSetConf(ctx, req.(*PGSetConfRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// PostgreSql_ServiceDesc is the grpc.ServiceDesc for PostgreSql service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PostgreSql_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "proto.PostgreSql",
	HandlerType: (*PostgreSqlServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "PGGetComposes",
			Handler:    _PostgreSql_PGGetComposes_Handler,
		},
		{
			MethodName: "PGOperation",
			Handler:    _PostgreSql_PGOperation_Handler,
		},
		{
			MethodName: "PGSetPort",
			Handler:    _PostgreSql_PGSetPort_Handler,
		},
		{
			MethodName: "PGGetConf",
			Handler:    _PostgreSql_PGGetConf_Handler,
		},
		{
			MethodName: "PGSetConf",
			Handler:    _PostgreSql_PGSetConf_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "postgresql.proto",
}
