// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v6.31.1
// source: redis.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	Redis_RedisGetComposes_FullMethodName     = "/proto.Redis/RedisGetComposes"
	Redis_RedisOperation_FullMethodName       = "/proto.Redis/RedisOperation"
	Redis_RedisSetPort_FullMethodName         = "/proto.Redis/RedisSetPort"
	Redis_RedisGetConf_FullMethodName         = "/proto.Redis/RedisGetConf"
	Redis_RedisSetConf_FullMethodName         = "/proto.Redis/RedisSetConf"
	Redis_RedisGetRemoteAccess_FullMethodName = "/proto.Redis/RedisGetRemoteAccess"
	Redis_RedisSetRemoteAccess_FullMethodName = "/proto.Redis/RedisSetRemoteAccess"
	Redis_RedisGetRootPassword_FullMethodName = "/proto.Redis/RedisGetRootPassword"
	Redis_RedisSetRootPassword_FullMethodName = "/proto.Redis/RedisSetRootPassword"
)

// RedisClient is the client API for Redis service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type RedisClient interface {
	RedisGetComposes(ctx context.Context, in *RedisGetComposesRequest, opts ...grpc.CallOption) (*RedisGetComposesResponse, error)
	RedisOperation(ctx context.Context, in *RedisOperationRequest, opts ...grpc.CallOption) (*RedisCommonResponse, error)
	RedisSetPort(ctx context.Context, in *RedisSetPortRequest, opts ...grpc.CallOption) (*RedisCommonResponse, error)
	RedisGetConf(ctx context.Context, in *RedisGetConfRequest, opts ...grpc.CallOption) (*RedisGetConfResponse, error)
	RedisSetConf(ctx context.Context, in *RedisSetConfRequest, opts ...grpc.CallOption) (*RedisCommonResponse, error)
	RedisGetRemoteAccess(ctx context.Context, in *RedisGetRemoteAccessRequest, opts ...grpc.CallOption) (*RedisGetRemoteAccessResponse, error)
	RedisSetRemoteAccess(ctx context.Context, in *RedisSetRemoteAccessRequest, opts ...grpc.CallOption) (*RedisCommonResponse, error)
	RedisGetRootPassword(ctx context.Context, in *RedisGetRootPasswordRequest, opts ...grpc.CallOption) (*RedisGetRootPasswordResponse, error)
	RedisSetRootPassword(ctx context.Context, in *RedisSetRootPasswordRequest, opts ...grpc.CallOption) (*RedisCommonResponse, error)
}

type redisClient struct {
	cc grpc.ClientConnInterface
}

func NewRedisClient(cc grpc.ClientConnInterface) RedisClient {
	return &redisClient{cc}
}

func (c *redisClient) RedisGetComposes(ctx context.Context, in *RedisGetComposesRequest, opts ...grpc.CallOption) (*RedisGetComposesResponse, error) {
	out := new(RedisGetComposesResponse)
	err := c.cc.Invoke(ctx, Redis_RedisGetComposes_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *redisClient) RedisOperation(ctx context.Context, in *RedisOperationRequest, opts ...grpc.CallOption) (*RedisCommonResponse, error) {
	out := new(RedisCommonResponse)
	err := c.cc.Invoke(ctx, Redis_RedisOperation_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *redisClient) RedisSetPort(ctx context.Context, in *RedisSetPortRequest, opts ...grpc.CallOption) (*RedisCommonResponse, error) {
	out := new(RedisCommonResponse)
	err := c.cc.Invoke(ctx, Redis_RedisSetPort_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *redisClient) RedisGetConf(ctx context.Context, in *RedisGetConfRequest, opts ...grpc.CallOption) (*RedisGetConfResponse, error) {
	out := new(RedisGetConfResponse)
	err := c.cc.Invoke(ctx, Redis_RedisGetConf_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *redisClient) RedisSetConf(ctx context.Context, in *RedisSetConfRequest, opts ...grpc.CallOption) (*RedisCommonResponse, error) {
	out := new(RedisCommonResponse)
	err := c.cc.Invoke(ctx, Redis_RedisSetConf_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *redisClient) RedisGetRemoteAccess(ctx context.Context, in *RedisGetRemoteAccessRequest, opts ...grpc.CallOption) (*RedisGetRemoteAccessResponse, error) {
	out := new(RedisGetRemoteAccessResponse)
	err := c.cc.Invoke(ctx, Redis_RedisGetRemoteAccess_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *redisClient) RedisSetRemoteAccess(ctx context.Context, in *RedisSetRemoteAccessRequest, opts ...grpc.CallOption) (*RedisCommonResponse, error) {
	out := new(RedisCommonResponse)
	err := c.cc.Invoke(ctx, Redis_RedisSetRemoteAccess_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *redisClient) RedisGetRootPassword(ctx context.Context, in *RedisGetRootPasswordRequest, opts ...grpc.CallOption) (*RedisGetRootPasswordResponse, error) {
	out := new(RedisGetRootPasswordResponse)
	err := c.cc.Invoke(ctx, Redis_RedisGetRootPassword_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *redisClient) RedisSetRootPassword(ctx context.Context, in *RedisSetRootPasswordRequest, opts ...grpc.CallOption) (*RedisCommonResponse, error) {
	out := new(RedisCommonResponse)
	err := c.cc.Invoke(ctx, Redis_RedisSetRootPassword_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RedisServer is the server API for Redis service.
// All implementations must embed UnimplementedRedisServer
// for forward compatibility
type RedisServer interface {
	RedisGetComposes(context.Context, *RedisGetComposesRequest) (*RedisGetComposesResponse, error)
	RedisOperation(context.Context, *RedisOperationRequest) (*RedisCommonResponse, error)
	RedisSetPort(context.Context, *RedisSetPortRequest) (*RedisCommonResponse, error)
	RedisGetConf(context.Context, *RedisGetConfRequest) (*RedisGetConfResponse, error)
	RedisSetConf(context.Context, *RedisSetConfRequest) (*RedisCommonResponse, error)
	RedisGetRemoteAccess(context.Context, *RedisGetRemoteAccessRequest) (*RedisGetRemoteAccessResponse, error)
	RedisSetRemoteAccess(context.Context, *RedisSetRemoteAccessRequest) (*RedisCommonResponse, error)
	RedisGetRootPassword(context.Context, *RedisGetRootPasswordRequest) (*RedisGetRootPasswordResponse, error)
	RedisSetRootPassword(context.Context, *RedisSetRootPasswordRequest) (*RedisCommonResponse, error)
	mustEmbedUnimplementedRedisServer()
}

// UnimplementedRedisServer must be embedded to have forward compatible implementations.
type UnimplementedRedisServer struct {
}

func (UnimplementedRedisServer) RedisGetComposes(context.Context, *RedisGetComposesRequest) (*RedisGetComposesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RedisGetComposes not implemented")
}
func (UnimplementedRedisServer) RedisOperation(context.Context, *RedisOperationRequest) (*RedisCommonResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RedisOperation not implemented")
}
func (UnimplementedRedisServer) RedisSetPort(context.Context, *RedisSetPortRequest) (*RedisCommonResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RedisSetPort not implemented")
}
func (UnimplementedRedisServer) RedisGetConf(context.Context, *RedisGetConfRequest) (*RedisGetConfResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RedisGetConf not implemented")
}
func (UnimplementedRedisServer) RedisSetConf(context.Context, *RedisSetConfRequest) (*RedisCommonResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RedisSetConf not implemented")
}
func (UnimplementedRedisServer) RedisGetRemoteAccess(context.Context, *RedisGetRemoteAccessRequest) (*RedisGetRemoteAccessResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RedisGetRemoteAccess not implemented")
}
func (UnimplementedRedisServer) RedisSetRemoteAccess(context.Context, *RedisSetRemoteAccessRequest) (*RedisCommonResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RedisSetRemoteAccess not implemented")
}
func (UnimplementedRedisServer) RedisGetRootPassword(context.Context, *RedisGetRootPasswordRequest) (*RedisGetRootPasswordResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RedisGetRootPassword not implemented")
}
func (UnimplementedRedisServer) RedisSetRootPassword(context.Context, *RedisSetRootPasswordRequest) (*RedisCommonResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RedisSetRootPassword not implemented")
}
func (UnimplementedRedisServer) mustEmbedUnimplementedRedisServer() {}

// UnsafeRedisServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RedisServer will
// result in compilation errors.
type UnsafeRedisServer interface {
	mustEmbedUnimplementedRedisServer()
}

func RegisterRedisServer(s grpc.ServiceRegistrar, srv RedisServer) {
	s.RegisterService(&Redis_ServiceDesc, srv)
}

func _Redis_RedisGetComposes_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RedisGetComposesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RedisServer).RedisGetComposes(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Redis_RedisGetComposes_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RedisServer).RedisGetComposes(ctx, req.(*RedisGetComposesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Redis_RedisOperation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RedisOperationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RedisServer).RedisOperation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Redis_RedisOperation_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RedisServer).RedisOperation(ctx, req.(*RedisOperationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Redis_RedisSetPort_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RedisSetPortRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RedisServer).RedisSetPort(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Redis_RedisSetPort_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RedisServer).RedisSetPort(ctx, req.(*RedisSetPortRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Redis_RedisGetConf_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RedisGetConfRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RedisServer).RedisGetConf(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Redis_RedisGetConf_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RedisServer).RedisGetConf(ctx, req.(*RedisGetConfRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Redis_RedisSetConf_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RedisSetConfRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RedisServer).RedisSetConf(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Redis_RedisSetConf_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RedisServer).RedisSetConf(ctx, req.(*RedisSetConfRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Redis_RedisGetRemoteAccess_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RedisGetRemoteAccessRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RedisServer).RedisGetRemoteAccess(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Redis_RedisGetRemoteAccess_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RedisServer).RedisGetRemoteAccess(ctx, req.(*RedisGetRemoteAccessRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Redis_RedisSetRemoteAccess_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RedisSetRemoteAccessRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RedisServer).RedisSetRemoteAccess(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Redis_RedisSetRemoteAccess_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RedisServer).RedisSetRemoteAccess(ctx, req.(*RedisSetRemoteAccessRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Redis_RedisGetRootPassword_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RedisGetRootPasswordRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RedisServer).RedisGetRootPassword(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Redis_RedisGetRootPassword_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RedisServer).RedisGetRootPassword(ctx, req.(*RedisGetRootPasswordRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Redis_RedisSetRootPassword_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RedisSetRootPasswordRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RedisServer).RedisSetRootPassword(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Redis_RedisSetRootPassword_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RedisServer).RedisSetRootPassword(ctx, req.(*RedisSetRootPasswordRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Redis_ServiceDesc is the grpc.ServiceDesc for Redis service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Redis_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "proto.Redis",
	HandlerType: (*RedisServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RedisGetComposes",
			Handler:    _Redis_RedisGetComposes_Handler,
		},
		{
			MethodName: "RedisOperation",
			Handler:    _Redis_RedisOperation_Handler,
		},
		{
			MethodName: "RedisSetPort",
			Handler:    _Redis_RedisSetPort_Handler,
		},
		{
			MethodName: "RedisGetConf",
			Handler:    _Redis_RedisGetConf_Handler,
		},
		{
			MethodName: "RedisSetConf",
			Handler:    _Redis_RedisSetConf_Handler,
		},
		{
			MethodName: "RedisGetRemoteAccess",
			Handler:    _Redis_RedisGetRemoteAccess_Handler,
		},
		{
			MethodName: "RedisSetRemoteAccess",
			Handler:    _Redis_RedisSetRemoteAccess_Handler,
		},
		{
			MethodName: "RedisGetRootPassword",
			Handler:    _Redis_RedisGetRootPassword_Handler,
		},
		{
			MethodName: "RedisSetRootPassword",
			Handler:    _Redis_RedisSetRootPassword_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "redis.proto",
}
