// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v6.31.1
// source: rsync.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	Rsync_RsyncListTask_FullMethodName   = "/proto.Rsync/RsyncListTask"
	Rsync_RsyncCreateTask_FullMethodName = "/proto.Rsync/RsyncCreateTask"
	Rsync_RsyncQueryTask_FullMethodName  = "/proto.Rsync/RsyncQueryTask"
	Rsync_RsyncCancelTask_FullMethodName = "/proto.Rsync/RsyncCancelTask"
	Rsync_RsyncDeleteTask_FullMethodName = "/proto.Rsync/RsyncDeleteTask"
	Rsync_RsyncRetryTask_FullMethodName  = "/proto.Rsync/RsyncRetryTask"
)

// RsyncClient is the client API for Rsync service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type RsyncClient interface {
	RsyncListTask(ctx context.Context, in *RsyncListTaskRequest, opts ...grpc.CallOption) (*RsyncListTaskResponse, error)
	RsyncCreateTask(ctx context.Context, in *RsyncCreateTaskRequest, opts ...grpc.CallOption) (*RsyncCreateTaskResponse, error)
	RsyncQueryTask(ctx context.Context, in *RsyncQueryTaskRequest, opts ...grpc.CallOption) (*RsyncTaskInfo, error)
	RsyncCancelTask(ctx context.Context, in *RsyncCancelTaskRequest, opts ...grpc.CallOption) (*RsyncCommonResponse, error)
	RsyncDeleteTask(ctx context.Context, in *RsyncDeleteTaskRequest, opts ...grpc.CallOption) (*RsyncCommonResponse, error)
	RsyncRetryTask(ctx context.Context, in *RsyncRetryTaskRequest, opts ...grpc.CallOption) (*RsyncCommonResponse, error)
}

type rsyncClient struct {
	cc grpc.ClientConnInterface
}

func NewRsyncClient(cc grpc.ClientConnInterface) RsyncClient {
	return &rsyncClient{cc}
}

func (c *rsyncClient) RsyncListTask(ctx context.Context, in *RsyncListTaskRequest, opts ...grpc.CallOption) (*RsyncListTaskResponse, error) {
	out := new(RsyncListTaskResponse)
	err := c.cc.Invoke(ctx, Rsync_RsyncListTask_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rsyncClient) RsyncCreateTask(ctx context.Context, in *RsyncCreateTaskRequest, opts ...grpc.CallOption) (*RsyncCreateTaskResponse, error) {
	out := new(RsyncCreateTaskResponse)
	err := c.cc.Invoke(ctx, Rsync_RsyncCreateTask_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rsyncClient) RsyncQueryTask(ctx context.Context, in *RsyncQueryTaskRequest, opts ...grpc.CallOption) (*RsyncTaskInfo, error) {
	out := new(RsyncTaskInfo)
	err := c.cc.Invoke(ctx, Rsync_RsyncQueryTask_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rsyncClient) RsyncCancelTask(ctx context.Context, in *RsyncCancelTaskRequest, opts ...grpc.CallOption) (*RsyncCommonResponse, error) {
	out := new(RsyncCommonResponse)
	err := c.cc.Invoke(ctx, Rsync_RsyncCancelTask_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rsyncClient) RsyncDeleteTask(ctx context.Context, in *RsyncDeleteTaskRequest, opts ...grpc.CallOption) (*RsyncCommonResponse, error) {
	out := new(RsyncCommonResponse)
	err := c.cc.Invoke(ctx, Rsync_RsyncDeleteTask_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rsyncClient) RsyncRetryTask(ctx context.Context, in *RsyncRetryTaskRequest, opts ...grpc.CallOption) (*RsyncCommonResponse, error) {
	out := new(RsyncCommonResponse)
	err := c.cc.Invoke(ctx, Rsync_RsyncRetryTask_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RsyncServer is the server API for Rsync service.
// All implementations must embed UnimplementedRsyncServer
// for forward compatibility
type RsyncServer interface {
	RsyncListTask(context.Context, *RsyncListTaskRequest) (*RsyncListTaskResponse, error)
	RsyncCreateTask(context.Context, *RsyncCreateTaskRequest) (*RsyncCreateTaskResponse, error)
	RsyncQueryTask(context.Context, *RsyncQueryTaskRequest) (*RsyncTaskInfo, error)
	RsyncCancelTask(context.Context, *RsyncCancelTaskRequest) (*RsyncCommonResponse, error)
	RsyncDeleteTask(context.Context, *RsyncDeleteTaskRequest) (*RsyncCommonResponse, error)
	RsyncRetryTask(context.Context, *RsyncRetryTaskRequest) (*RsyncCommonResponse, error)
	mustEmbedUnimplementedRsyncServer()
}

// UnimplementedRsyncServer must be embedded to have forward compatible implementations.
type UnimplementedRsyncServer struct {
}

func (UnimplementedRsyncServer) RsyncListTask(context.Context, *RsyncListTaskRequest) (*RsyncListTaskResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RsyncListTask not implemented")
}
func (UnimplementedRsyncServer) RsyncCreateTask(context.Context, *RsyncCreateTaskRequest) (*RsyncCreateTaskResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RsyncCreateTask not implemented")
}
func (UnimplementedRsyncServer) RsyncQueryTask(context.Context, *RsyncQueryTaskRequest) (*RsyncTaskInfo, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RsyncQueryTask not implemented")
}
func (UnimplementedRsyncServer) RsyncCancelTask(context.Context, *RsyncCancelTaskRequest) (*RsyncCommonResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RsyncCancelTask not implemented")
}
func (UnimplementedRsyncServer) RsyncDeleteTask(context.Context, *RsyncDeleteTaskRequest) (*RsyncCommonResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RsyncDeleteTask not implemented")
}
func (UnimplementedRsyncServer) RsyncRetryTask(context.Context, *RsyncRetryTaskRequest) (*RsyncCommonResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RsyncRetryTask not implemented")
}
func (UnimplementedRsyncServer) mustEmbedUnimplementedRsyncServer() {}

// UnsafeRsyncServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RsyncServer will
// result in compilation errors.
type UnsafeRsyncServer interface {
	mustEmbedUnimplementedRsyncServer()
}

func RegisterRsyncServer(s grpc.ServiceRegistrar, srv RsyncServer) {
	s.RegisterService(&Rsync_ServiceDesc, srv)
}

func _Rsync_RsyncListTask_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RsyncListTaskRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RsyncServer).RsyncListTask(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Rsync_RsyncListTask_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RsyncServer).RsyncListTask(ctx, req.(*RsyncListTaskRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Rsync_RsyncCreateTask_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RsyncCreateTaskRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RsyncServer).RsyncCreateTask(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Rsync_RsyncCreateTask_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RsyncServer).RsyncCreateTask(ctx, req.(*RsyncCreateTaskRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Rsync_RsyncQueryTask_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RsyncQueryTaskRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RsyncServer).RsyncQueryTask(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Rsync_RsyncQueryTask_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RsyncServer).RsyncQueryTask(ctx, req.(*RsyncQueryTaskRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Rsync_RsyncCancelTask_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RsyncCancelTaskRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RsyncServer).RsyncCancelTask(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Rsync_RsyncCancelTask_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RsyncServer).RsyncCancelTask(ctx, req.(*RsyncCancelTaskRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Rsync_RsyncDeleteTask_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RsyncDeleteTaskRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RsyncServer).RsyncDeleteTask(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Rsync_RsyncDeleteTask_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RsyncServer).RsyncDeleteTask(ctx, req.(*RsyncDeleteTaskRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Rsync_RsyncRetryTask_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RsyncRetryTaskRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RsyncServer).RsyncRetryTask(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Rsync_RsyncRetryTask_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RsyncServer).RsyncRetryTask(ctx, req.(*RsyncRetryTaskRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Rsync_ServiceDesc is the grpc.ServiceDesc for Rsync service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Rsync_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "proto.Rsync",
	HandlerType: (*RsyncServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RsyncListTask",
			Handler:    _Rsync_RsyncListTask_Handler,
		},
		{
			MethodName: "RsyncCreateTask",
			Handler:    _Rsync_RsyncCreateTask_Handler,
		},
		{
			MethodName: "RsyncQueryTask",
			Handler:    _Rsync_RsyncQueryTask_Handler,
		},
		{
			MethodName: "RsyncCancelTask",
			Handler:    _Rsync_RsyncCancelTask_Handler,
		},
		{
			MethodName: "RsyncDeleteTask",
			Handler:    _Rsync_RsyncDeleteTask_Handler,
		},
		{
			MethodName: "RsyncRetryTask",
			Handler:    _Rsync_RsyncRetryTask_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "rsync.proto",
}
