// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.33.0
// 	protoc        v6.31.1
// source: rsync.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RsyncCommonResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Success bool   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error   string `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
}

func (x *RsyncCommonResponse) Reset() {
	*x = RsyncCommonResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rsync_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RsyncCommonResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RsyncCommonResponse) ProtoMessage() {}

func (x *RsyncCommonResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rsync_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RsyncCommonResponse.ProtoReflect.Descriptor instead.
func (*RsyncCommonResponse) Descriptor() ([]byte, []int) {
	return file_rsync_proto_rawDescGZIP(), []int{0}
}

func (x *RsyncCommonResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *RsyncCommonResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type RsyncListTaskRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Page     int32 `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	PageSize int32 `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
}

func (x *RsyncListTaskRequest) Reset() {
	*x = RsyncListTaskRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rsync_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RsyncListTaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RsyncListTaskRequest) ProtoMessage() {}

func (x *RsyncListTaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rsync_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RsyncListTaskRequest.ProtoReflect.Descriptor instead.
func (*RsyncListTaskRequest) Descriptor() ([]byte, []int) {
	return file_rsync_proto_rawDescGZIP(), []int{1}
}

func (x *RsyncListTaskRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *RsyncListTaskRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type RsyncListTaskResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Total int64            `protobuf:"varint,1,opt,name=total,proto3" json:"total,omitempty"`
	Items []*RsyncTaskInfo `protobuf:"bytes,2,rep,name=items,proto3" json:"items,omitempty"`
}

func (x *RsyncListTaskResponse) Reset() {
	*x = RsyncListTaskResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rsync_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RsyncListTaskResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RsyncListTaskResponse) ProtoMessage() {}

func (x *RsyncListTaskResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rsync_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RsyncListTaskResponse.ProtoReflect.Descriptor instead.
func (*RsyncListTaskResponse) Descriptor() ([]byte, []int) {
	return file_rsync_proto_rawDescGZIP(), []int{2}
}

func (x *RsyncListTaskResponse) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *RsyncListTaskResponse) GetItems() []*RsyncTaskInfo {
	if x != nil {
		return x.Items
	}
	return nil
}

type RsyncTaskInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id        string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Src       string `protobuf:"bytes,2,opt,name=src,proto3" json:"src,omitempty"`
	Dst       string `protobuf:"bytes,3,opt,name=dst,proto3" json:"dst,omitempty"`
	CacheDir  string `protobuf:"bytes,4,opt,name=cache_dir,json=cacheDir,proto3" json:"cache_dir,omitempty"`
	Mode      string `protobuf:"bytes,5,opt,name=mode,proto3" json:"mode,omitempty"`
	Status    string `protobuf:"bytes,6,opt,name=status,proto3" json:"status,omitempty"`
	Progress  int32  `protobuf:"varint,7,opt,name=progress,proto3" json:"progress,omitempty"`
	Step      string `protobuf:"bytes,8,opt,name=step,proto3" json:"step,omitempty"`
	StartTime string `protobuf:"bytes,9,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	EndTime   string `protobuf:"bytes,10,opt,name=end_time,json=endTime,proto3" json:"end_time,omitempty"`
	Error     string `protobuf:"bytes,11,opt,name=error,proto3" json:"error,omitempty"`
	LastLog   string `protobuf:"bytes,12,opt,name=last_log,json=lastLog,proto3" json:"last_log,omitempty"`
}

func (x *RsyncTaskInfo) Reset() {
	*x = RsyncTaskInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rsync_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RsyncTaskInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RsyncTaskInfo) ProtoMessage() {}

func (x *RsyncTaskInfo) ProtoReflect() protoreflect.Message {
	mi := &file_rsync_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RsyncTaskInfo.ProtoReflect.Descriptor instead.
func (*RsyncTaskInfo) Descriptor() ([]byte, []int) {
	return file_rsync_proto_rawDescGZIP(), []int{3}
}

func (x *RsyncTaskInfo) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *RsyncTaskInfo) GetSrc() string {
	if x != nil {
		return x.Src
	}
	return ""
}

func (x *RsyncTaskInfo) GetDst() string {
	if x != nil {
		return x.Dst
	}
	return ""
}

func (x *RsyncTaskInfo) GetCacheDir() string {
	if x != nil {
		return x.CacheDir
	}
	return ""
}

func (x *RsyncTaskInfo) GetMode() string {
	if x != nil {
		return x.Mode
	}
	return ""
}

func (x *RsyncTaskInfo) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *RsyncTaskInfo) GetProgress() int32 {
	if x != nil {
		return x.Progress
	}
	return 0
}

func (x *RsyncTaskInfo) GetStep() string {
	if x != nil {
		return x.Step
	}
	return ""
}

func (x *RsyncTaskInfo) GetStartTime() string {
	if x != nil {
		return x.StartTime
	}
	return ""
}

func (x *RsyncTaskInfo) GetEndTime() string {
	if x != nil {
		return x.EndTime
	}
	return ""
}

func (x *RsyncTaskInfo) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *RsyncTaskInfo) GetLastLog() string {
	if x != nil {
		return x.LastLog
	}
	return ""
}

type RsyncHost struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Host     string `protobuf:"bytes,1,opt,name=host,proto3" json:"host,omitempty"`
	Port     int32  `protobuf:"varint,2,opt,name=port,proto3" json:"port,omitempty"`
	User     string `protobuf:"bytes,3,opt,name=user,proto3" json:"user,omitempty"`
	KeyPath  string `protobuf:"bytes,4,opt,name=key_path,json=keyPath,proto3" json:"key_path,omitempty"`
	Password string `protobuf:"bytes,5,opt,name=password,proto3" json:"password,omitempty"`
}

func (x *RsyncHost) Reset() {
	*x = RsyncHost{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rsync_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RsyncHost) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RsyncHost) ProtoMessage() {}

func (x *RsyncHost) ProtoReflect() protoreflect.Message {
	mi := &file_rsync_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RsyncHost.ProtoReflect.Descriptor instead.
func (*RsyncHost) Descriptor() ([]byte, []int) {
	return file_rsync_proto_rawDescGZIP(), []int{4}
}

func (x *RsyncHost) GetHost() string {
	if x != nil {
		return x.Host
	}
	return ""
}

func (x *RsyncHost) GetPort() int32 {
	if x != nil {
		return x.Port
	}
	return 0
}

func (x *RsyncHost) GetUser() string {
	if x != nil {
		return x.User
	}
	return ""
}

func (x *RsyncHost) GetKeyPath() string {
	if x != nil {
		return x.KeyPath
	}
	return ""
}

func (x *RsyncHost) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type RsyncCreateTaskRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Src     string     `protobuf:"bytes,1,opt,name=src,proto3" json:"src,omitempty"`
	SrcHost *RsyncHost `protobuf:"bytes,2,opt,name=src_host,json=srcHost,proto3" json:"src_host,omitempty"`
	Dst     string     `protobuf:"bytes,3,opt,name=dst,proto3" json:"dst,omitempty"`
	DstHost *RsyncHost `protobuf:"bytes,4,opt,name=dst_host,json=dstHost,proto3" json:"dst_host,omitempty"`
	Mode    string     `protobuf:"bytes,5,opt,name=mode,proto3" json:"mode,omitempty"`
}

func (x *RsyncCreateTaskRequest) Reset() {
	*x = RsyncCreateTaskRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rsync_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RsyncCreateTaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RsyncCreateTaskRequest) ProtoMessage() {}

func (x *RsyncCreateTaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rsync_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RsyncCreateTaskRequest.ProtoReflect.Descriptor instead.
func (*RsyncCreateTaskRequest) Descriptor() ([]byte, []int) {
	return file_rsync_proto_rawDescGZIP(), []int{5}
}

func (x *RsyncCreateTaskRequest) GetSrc() string {
	if x != nil {
		return x.Src
	}
	return ""
}

func (x *RsyncCreateTaskRequest) GetSrcHost() *RsyncHost {
	if x != nil {
		return x.SrcHost
	}
	return nil
}

func (x *RsyncCreateTaskRequest) GetDst() string {
	if x != nil {
		return x.Dst
	}
	return ""
}

func (x *RsyncCreateTaskRequest) GetDstHost() *RsyncHost {
	if x != nil {
		return x.DstHost
	}
	return nil
}

func (x *RsyncCreateTaskRequest) GetMode() string {
	if x != nil {
		return x.Mode
	}
	return ""
}

type RsyncCreateTaskResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *RsyncCreateTaskResponse) Reset() {
	*x = RsyncCreateTaskResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rsync_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RsyncCreateTaskResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RsyncCreateTaskResponse) ProtoMessage() {}

func (x *RsyncCreateTaskResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rsync_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RsyncCreateTaskResponse.ProtoReflect.Descriptor instead.
func (*RsyncCreateTaskResponse) Descriptor() ([]byte, []int) {
	return file_rsync_proto_rawDescGZIP(), []int{6}
}

func (x *RsyncCreateTaskResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type RsyncQueryTaskRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *RsyncQueryTaskRequest) Reset() {
	*x = RsyncQueryTaskRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rsync_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RsyncQueryTaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RsyncQueryTaskRequest) ProtoMessage() {}

func (x *RsyncQueryTaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rsync_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RsyncQueryTaskRequest.ProtoReflect.Descriptor instead.
func (*RsyncQueryTaskRequest) Descriptor() ([]byte, []int) {
	return file_rsync_proto_rawDescGZIP(), []int{7}
}

func (x *RsyncQueryTaskRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type RsyncCancelTaskRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *RsyncCancelTaskRequest) Reset() {
	*x = RsyncCancelTaskRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rsync_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RsyncCancelTaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RsyncCancelTaskRequest) ProtoMessage() {}

func (x *RsyncCancelTaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rsync_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RsyncCancelTaskRequest.ProtoReflect.Descriptor instead.
func (*RsyncCancelTaskRequest) Descriptor() ([]byte, []int) {
	return file_rsync_proto_rawDescGZIP(), []int{8}
}

func (x *RsyncCancelTaskRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type RsyncDeleteTaskRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *RsyncDeleteTaskRequest) Reset() {
	*x = RsyncDeleteTaskRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rsync_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RsyncDeleteTaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RsyncDeleteTaskRequest) ProtoMessage() {}

func (x *RsyncDeleteTaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rsync_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RsyncDeleteTaskRequest.ProtoReflect.Descriptor instead.
func (*RsyncDeleteTaskRequest) Descriptor() ([]byte, []int) {
	return file_rsync_proto_rawDescGZIP(), []int{9}
}

func (x *RsyncDeleteTaskRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type RsyncRetryTaskRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *RsyncRetryTaskRequest) Reset() {
	*x = RsyncRetryTaskRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rsync_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RsyncRetryTaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RsyncRetryTaskRequest) ProtoMessage() {}

func (x *RsyncRetryTaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rsync_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RsyncRetryTaskRequest.ProtoReflect.Descriptor instead.
func (*RsyncRetryTaskRequest) Descriptor() ([]byte, []int) {
	return file_rsync_proto_rawDescGZIP(), []int{10}
}

func (x *RsyncRetryTaskRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

var File_rsync_proto protoreflect.FileDescriptor

var file_rsync_proto_rawDesc = []byte{
	0x0a, 0x0b, 0x72, 0x73, 0x79, 0x6e, 0x63, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x22, 0x45, 0x0a, 0x13, 0x52, 0x73, 0x79, 0x6e, 0x63, 0x43, 0x6f, 0x6d,
	0x6d, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x73,
	0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x73, 0x75,
	0x63, 0x63, 0x65, 0x73, 0x73, 0x12, 0x14, 0x0a, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x22, 0x47, 0x0a, 0x14, 0x52,
	0x73, 0x79, 0x6e, 0x63, 0x4c, 0x69, 0x73, 0x74, 0x54, 0x61, 0x73, 0x6b, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x70, 0x61, 0x67, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x04, 0x70, 0x61, 0x67, 0x65, 0x12, 0x1b, 0x0a, 0x09, 0x70, 0x61, 0x67, 0x65, 0x5f,
	0x73, 0x69, 0x7a, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x70, 0x61, 0x67, 0x65,
	0x53, 0x69, 0x7a, 0x65, 0x22, 0x59, 0x0a, 0x15, 0x52, 0x73, 0x79, 0x6e, 0x63, 0x4c, 0x69, 0x73,
	0x74, 0x54, 0x61, 0x73, 0x6b, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x14, 0x0a,
	0x05, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x74, 0x6f,
	0x74, 0x61, 0x6c, 0x12, 0x2a, 0x0a, 0x05, 0x69, 0x74, 0x65, 0x6d, 0x73, 0x18, 0x02, 0x20, 0x03,
	0x28, 0x0b, 0x32, 0x14, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x52, 0x73, 0x79, 0x6e, 0x63,
	0x54, 0x61, 0x73, 0x6b, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x05, 0x69, 0x74, 0x65, 0x6d, 0x73, 0x22,
	0xa7, 0x02, 0x0a, 0x0d, 0x52, 0x73, 0x79, 0x6e, 0x63, 0x54, 0x61, 0x73, 0x6b, 0x49, 0x6e, 0x66,
	0x6f, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69,
	0x64, 0x12, 0x10, 0x0a, 0x03, 0x73, 0x72, 0x63, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03,
	0x73, 0x72, 0x63, 0x12, 0x10, 0x0a, 0x03, 0x64, 0x73, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x03, 0x64, 0x73, 0x74, 0x12, 0x1b, 0x0a, 0x09, 0x63, 0x61, 0x63, 0x68, 0x65, 0x5f, 0x64,
	0x69, 0x72, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x63, 0x61, 0x63, 0x68, 0x65, 0x44,
	0x69, 0x72, 0x12, 0x12, 0x0a, 0x04, 0x6d, 0x6f, 0x64, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x04, 0x6d, 0x6f, 0x64, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73,
	0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x1a,
	0x0a, 0x08, 0x70, 0x72, 0x6f, 0x67, 0x72, 0x65, 0x73, 0x73, 0x18, 0x07, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x08, 0x70, 0x72, 0x6f, 0x67, 0x72, 0x65, 0x73, 0x73, 0x12, 0x12, 0x0a, 0x04, 0x73, 0x74,
	0x65, 0x70, 0x18, 0x08, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x73, 0x74, 0x65, 0x70, 0x12, 0x1d,
	0x0a, 0x0a, 0x73, 0x74, 0x61, 0x72, 0x74, 0x5f, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x09, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x09, 0x73, 0x74, 0x61, 0x72, 0x74, 0x54, 0x69, 0x6d, 0x65, 0x12, 0x19, 0x0a,
	0x08, 0x65, 0x6e, 0x64, 0x5f, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x07, 0x65, 0x6e, 0x64, 0x54, 0x69, 0x6d, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x65, 0x72, 0x72, 0x6f,
	0x72, 0x18, 0x0b, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x12, 0x19,
	0x0a, 0x08, 0x6c, 0x61, 0x73, 0x74, 0x5f, 0x6c, 0x6f, 0x67, 0x18, 0x0c, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x07, 0x6c, 0x61, 0x73, 0x74, 0x4c, 0x6f, 0x67, 0x22, 0x7e, 0x0a, 0x09, 0x52, 0x73, 0x79,
	0x6e, 0x63, 0x48, 0x6f, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x68, 0x6f, 0x73, 0x74, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x68, 0x6f, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x70, 0x6f,
	0x72, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x70, 0x6f, 0x72, 0x74, 0x12, 0x12,
	0x0a, 0x04, 0x75, 0x73, 0x65, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x75, 0x73,
	0x65, 0x72, 0x12, 0x19, 0x0a, 0x08, 0x6b, 0x65, 0x79, 0x5f, 0x70, 0x61, 0x74, 0x68, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6b, 0x65, 0x79, 0x50, 0x61, 0x74, 0x68, 0x12, 0x1a, 0x0a,
	0x08, 0x70, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x08, 0x70, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x22, 0xaa, 0x01, 0x0a, 0x16, 0x52, 0x73,
	0x79, 0x6e, 0x63, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x54, 0x61, 0x73, 0x6b, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x73, 0x72, 0x63, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x03, 0x73, 0x72, 0x63, 0x12, 0x2b, 0x0a, 0x08, 0x73, 0x72, 0x63, 0x5f, 0x68, 0x6f,
	0x73, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x2e, 0x52, 0x73, 0x79, 0x6e, 0x63, 0x48, 0x6f, 0x73, 0x74, 0x52, 0x07, 0x73, 0x72, 0x63, 0x48,
	0x6f, 0x73, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x64, 0x73, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x03, 0x64, 0x73, 0x74, 0x12, 0x2b, 0x0a, 0x08, 0x64, 0x73, 0x74, 0x5f, 0x68, 0x6f, 0x73,
	0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e,
	0x52, 0x73, 0x79, 0x6e, 0x63, 0x48, 0x6f, 0x73, 0x74, 0x52, 0x07, 0x64, 0x73, 0x74, 0x48, 0x6f,
	0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x6d, 0x6f, 0x64, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x04, 0x6d, 0x6f, 0x64, 0x65, 0x22, 0x29, 0x0a, 0x17, 0x52, 0x73, 0x79, 0x6e, 0x63, 0x43,
	0x72, 0x65, 0x61, 0x74, 0x65, 0x54, 0x61, 0x73, 0x6b, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69,
	0x64, 0x22, 0x27, 0x0a, 0x15, 0x52, 0x73, 0x79, 0x6e, 0x63, 0x51, 0x75, 0x65, 0x72, 0x79, 0x54,
	0x61, 0x73, 0x6b, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x22, 0x28, 0x0a, 0x16, 0x52, 0x73,
	0x79, 0x6e, 0x63, 0x43, 0x61, 0x6e, 0x63, 0x65, 0x6c, 0x54, 0x61, 0x73, 0x6b, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x02, 0x69, 0x64, 0x22, 0x28, 0x0a, 0x16, 0x52, 0x73, 0x79, 0x6e, 0x63, 0x44, 0x65, 0x6c,
	0x65, 0x74, 0x65, 0x54, 0x61, 0x73, 0x6b, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e,
	0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x22, 0x27,
	0x0a, 0x15, 0x52, 0x73, 0x79, 0x6e, 0x63, 0x52, 0x65, 0x74, 0x72, 0x79, 0x54, 0x61, 0x73, 0x6b,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x32, 0xdf, 0x03, 0x0a, 0x05, 0x52, 0x73, 0x79, 0x6e,
	0x63, 0x12, 0x4c, 0x0a, 0x0d, 0x52, 0x73, 0x79, 0x6e, 0x63, 0x4c, 0x69, 0x73, 0x74, 0x54, 0x61,
	0x73, 0x6b, 0x12, 0x1b, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x52, 0x73, 0x79, 0x6e, 0x63,
	0x4c, 0x69, 0x73, 0x74, 0x54, 0x61, 0x73, 0x6b, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a,
	0x1c, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x52, 0x73, 0x79, 0x6e, 0x63, 0x4c, 0x69, 0x73,
	0x74, 0x54, 0x61, 0x73, 0x6b, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12,
	0x52, 0x0a, 0x0f, 0x52, 0x73, 0x79, 0x6e, 0x63, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x54, 0x61,
	0x73, 0x6b, 0x12, 0x1d, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x52, 0x73, 0x79, 0x6e, 0x63,
	0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x54, 0x61, 0x73, 0x6b, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x1e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x52, 0x73, 0x79, 0x6e, 0x63, 0x43,
	0x72, 0x65, 0x61, 0x74, 0x65, 0x54, 0x61, 0x73, 0x6b, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x22, 0x00, 0x12, 0x46, 0x0a, 0x0e, 0x52, 0x73, 0x79, 0x6e, 0x63, 0x51, 0x75, 0x65, 0x72,
	0x79, 0x54, 0x61, 0x73, 0x6b, 0x12, 0x1c, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x52, 0x73,
	0x79, 0x6e, 0x63, 0x51, 0x75, 0x65, 0x72, 0x79, 0x54, 0x61, 0x73, 0x6b, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x1a, 0x14, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x52, 0x73, 0x79, 0x6e,
	0x63, 0x54, 0x61, 0x73, 0x6b, 0x49, 0x6e, 0x66, 0x6f, 0x22, 0x00, 0x12, 0x4e, 0x0a, 0x0f, 0x52,
	0x73, 0x79, 0x6e, 0x63, 0x43, 0x61, 0x6e, 0x63, 0x65, 0x6c, 0x54, 0x61, 0x73, 0x6b, 0x12, 0x1d,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x52, 0x73, 0x79, 0x6e, 0x63, 0x43, 0x61, 0x6e, 0x63,
	0x65, 0x6c, 0x54, 0x61, 0x73, 0x6b, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1a, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x52, 0x73, 0x79, 0x6e, 0x63, 0x43, 0x6f, 0x6d, 0x6d, 0x6f,
	0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x4e, 0x0a, 0x0f, 0x52,
	0x73, 0x79, 0x6e, 0x63, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x54, 0x61, 0x73, 0x6b, 0x12, 0x1d,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x52, 0x73, 0x79, 0x6e, 0x63, 0x44, 0x65, 0x6c, 0x65,
	0x74, 0x65, 0x54, 0x61, 0x73, 0x6b, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1a, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x52, 0x73, 0x79, 0x6e, 0x63, 0x43, 0x6f, 0x6d, 0x6d, 0x6f,
	0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x4c, 0x0a, 0x0e, 0x52,
	0x73, 0x79, 0x6e, 0x63, 0x52, 0x65, 0x74, 0x72, 0x79, 0x54, 0x61, 0x73, 0x6b, 0x12, 0x1c, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x52, 0x73, 0x79, 0x6e, 0x63, 0x52, 0x65, 0x74, 0x72, 0x79,
	0x54, 0x61, 0x73, 0x6b, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1a, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x2e, 0x52, 0x73, 0x79, 0x6e, 0x63, 0x43, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x0a, 0x5a, 0x08, 0x2e, 0x2e, 0x2f,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_rsync_proto_rawDescOnce sync.Once
	file_rsync_proto_rawDescData = file_rsync_proto_rawDesc
)

func file_rsync_proto_rawDescGZIP() []byte {
	file_rsync_proto_rawDescOnce.Do(func() {
		file_rsync_proto_rawDescData = protoimpl.X.CompressGZIP(file_rsync_proto_rawDescData)
	})
	return file_rsync_proto_rawDescData
}

var file_rsync_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_rsync_proto_goTypes = []interface{}{
	(*RsyncCommonResponse)(nil),     // 0: proto.RsyncCommonResponse
	(*RsyncListTaskRequest)(nil),    // 1: proto.RsyncListTaskRequest
	(*RsyncListTaskResponse)(nil),   // 2: proto.RsyncListTaskResponse
	(*RsyncTaskInfo)(nil),           // 3: proto.RsyncTaskInfo
	(*RsyncHost)(nil),               // 4: proto.RsyncHost
	(*RsyncCreateTaskRequest)(nil),  // 5: proto.RsyncCreateTaskRequest
	(*RsyncCreateTaskResponse)(nil), // 6: proto.RsyncCreateTaskResponse
	(*RsyncQueryTaskRequest)(nil),   // 7: proto.RsyncQueryTaskRequest
	(*RsyncCancelTaskRequest)(nil),  // 8: proto.RsyncCancelTaskRequest
	(*RsyncDeleteTaskRequest)(nil),  // 9: proto.RsyncDeleteTaskRequest
	(*RsyncRetryTaskRequest)(nil),   // 10: proto.RsyncRetryTaskRequest
}
var file_rsync_proto_depIdxs = []int32{
	3,  // 0: proto.RsyncListTaskResponse.items:type_name -> proto.RsyncTaskInfo
	4,  // 1: proto.RsyncCreateTaskRequest.src_host:type_name -> proto.RsyncHost
	4,  // 2: proto.RsyncCreateTaskRequest.dst_host:type_name -> proto.RsyncHost
	1,  // 3: proto.Rsync.RsyncListTask:input_type -> proto.RsyncListTaskRequest
	5,  // 4: proto.Rsync.RsyncCreateTask:input_type -> proto.RsyncCreateTaskRequest
	7,  // 5: proto.Rsync.RsyncQueryTask:input_type -> proto.RsyncQueryTaskRequest
	8,  // 6: proto.Rsync.RsyncCancelTask:input_type -> proto.RsyncCancelTaskRequest
	9,  // 7: proto.Rsync.RsyncDeleteTask:input_type -> proto.RsyncDeleteTaskRequest
	10, // 8: proto.Rsync.RsyncRetryTask:input_type -> proto.RsyncRetryTaskRequest
	2,  // 9: proto.Rsync.RsyncListTask:output_type -> proto.RsyncListTaskResponse
	6,  // 10: proto.Rsync.RsyncCreateTask:output_type -> proto.RsyncCreateTaskResponse
	3,  // 11: proto.Rsync.RsyncQueryTask:output_type -> proto.RsyncTaskInfo
	0,  // 12: proto.Rsync.RsyncCancelTask:output_type -> proto.RsyncCommonResponse
	0,  // 13: proto.Rsync.RsyncDeleteTask:output_type -> proto.RsyncCommonResponse
	0,  // 14: proto.Rsync.RsyncRetryTask:output_type -> proto.RsyncCommonResponse
	9,  // [9:15] is the sub-list for method output_type
	3,  // [3:9] is the sub-list for method input_type
	3,  // [3:3] is the sub-list for extension type_name
	3,  // [3:3] is the sub-list for extension extendee
	0,  // [0:3] is the sub-list for field type_name
}

func init() { file_rsync_proto_init() }
func file_rsync_proto_init() {
	if File_rsync_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_rsync_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RsyncCommonResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rsync_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RsyncListTaskRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rsync_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RsyncListTaskResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rsync_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RsyncTaskInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rsync_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RsyncHost); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rsync_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RsyncCreateTaskRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rsync_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RsyncCreateTaskResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rsync_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RsyncQueryTaskRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rsync_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RsyncCancelTaskRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rsync_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RsyncDeleteTaskRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rsync_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RsyncRetryTaskRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_rsync_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_rsync_proto_goTypes,
		DependencyIndexes: file_rsync_proto_depIdxs,
		MessageInfos:      file_rsync_proto_msgTypes,
	}.Build()
	File_rsync_proto = out.File
	file_rsync_proto_rawDesc = nil
	file_rsync_proto_goTypes = nil
	file_rsync_proto_depIdxs = nil
}
