#!/bin/bash

set -euo pipefail

SCRIPT_DIR=$(
    cd "$(dirname "$0")"
    pwd
)

COMMON_FILE="${SCRIPT_DIR}/lib/common.sh"
SRC_DIR="${SCRIPT_DIR}/src"

function build_script() {
    local name="$1"
    local source_file="${SRC_DIR}/${name}.sh"
    local output_file="${SCRIPT_DIR}/${name}.sh"

    awk -v common_file="${COMMON_FILE}" '
        BEGIN {
            while ((getline line < common_file) > 0) {
                common_lines[++common_count] = line
            }
            close(common_file)
        }
        /^# __IDB_COMMON__$/ {
            print "# This file is generated by scripts/build-release-scripts.sh. Do not edit directly."
            print ""
            for (i = 1; i <= common_count; i++) {
                print common_lines[i]
            }
            next
        }
        { print }
    ' "${source_file}" > "${output_file}"

    chmod +x "${output_file}"
}

build_script install
build_script upgrade
