#!/bin/bash

set -euo pipefail

CURRENT_DIR=$(
    cd "$(dirname "$0")"
    pwd
)

IDB_DEFAULT_PROXY="https://dl.idb.net"
IDB_INSTALL_ROOT="/var/lib/idb"
IDB_HOME_DIR="${IDB_INSTALL_ROOT}/home"
IDB_DATA_DIR="${IDB_INSTALL_ROOT}/data"
IDB_AGENT_DIR="${IDB_INSTALL_ROOT}/agent"
IDB_PLUGIN_DIR="${IDB_DATA_DIR}/plugins"
IDB_LOG_DIR="/var/log/idb"
IDB_RUN_DIR="/run/idb"
IDB_CONF_DIR="/etc/idb"
IDB_AGENT_CONF_DIR="/etc/idb-agent"
TMP_DIR="/tmp/idb-upgrade"

IDB_DOCKER_USER=""
IDB_DOCKER_HOME=""
AGENT_INSTALL_FAILED="false"
AGENT_INSTALL_ERROR=""

function log() {
    local timestamp
    local message

    timestamp=$(date '+%Y-%m-%d %H:%M:%S')
    message="[${timestamp}] [idb Log] $1"
    echo -e "${message}" 2>&1 | tee -a "${CURRENT_DIR}/upgrade.log"
}

# This file is generated by scripts/build-release-scripts.sh. Do not edit directly.

function Probe_HTTP_200() {
    local url="$1"
    local attempts="${2:-3}"
    local i
    local code

    for ((i = 1; i <= attempts; i++)); do
        code=$(curl -s --connect-timeout 5 --max-time 10 -o /dev/null -w "%{http_code}" "$url" 2>/dev/null)
        if [[ "$code" == "200" ]]; then
            return 0
        fi
        sleep 1
    done

    return 1
}

function Fetch_Latest_Release_Tag() {
    local api_url="$1"
    local latest_url="${api_url}/repos/sensdata/idb/releases/latest?ts=$(date +%s)"

    curl -fsSL \
        -H "Accept: application/vnd.github.v3+json" \
        -H "Cache-Control: no-cache" \
        -H "Pragma: no-cache" \
        "${latest_url}" | sed -n 's/.*"tag_name"[[:space:]]*:[[:space:]]*"\([^"]*\)".*/\1/p' | head -n1
}

function Is_China_Region() {
    local country
    local tz

    country=$(curl -s --connect-timeout 3 --max-time 5 https://ipinfo.io/country 2>/dev/null | tr -d '[:space:]')
    if [[ "$country" == "CN" || "$country" == "HK" || "$country" == "MO" ]]; then
        return 0
    fi

    tz=$(timedatectl 2>/dev/null | grep "Time zone" | awk '{print $3}')
    [[ -z "$tz" ]] && tz="${TZ:-}"
    if [[ "$tz" == *"Shanghai"* || "$tz" == *"Chongqing"* || "$tz" == *"Hong_Kong"* ]]; then
        return 0
    fi
    return 1
}

function Auto_Detect_Proxy() {
    if [[ -n "${IDB_GITHUB_PROXY:-}" ]]; then
        log "使用指定代理: ${IDB_GITHUB_PROXY}"
        return
    fi

    if Is_China_Region; then
        log "检测到中国区域，优先检测加速代理..."
        if Probe_HTTP_200 "${IDB_DEFAULT_PROXY}/github-api/repos/sensdata/idb/releases/latest"; then
            export IDB_GITHUB_PROXY="${IDB_DEFAULT_PROXY}"
            log "加速代理可用: ${IDB_GITHUB_PROXY}"
            return
        fi
    fi

    if Probe_HTTP_200 "https://api.github.com/repos/sensdata/idb/releases/latest"; then
        log "GitHub 直连正常"
        return
    fi

    if Probe_HTTP_200 "${IDB_DEFAULT_PROXY}/github-api/repos/sensdata/idb/releases/latest"; then
        export IDB_GITHUB_PROXY="${IDB_DEFAULT_PROXY}"
        log "GitHub 直连不可用，切换到加速代理: ${IDB_GITHUB_PROXY}"
        return
    fi

    log "所有源均不可用，后续下载可能失败"
}

function Check_Root() {
    if [[ $EUID -ne 0 ]]; then
        log "请使用 root 或 sudo 权限运行此脚本"
        exit 1
    fi
}

function Check_Architecture() {
    local arch
    arch=$(uname -m)
    case "$arch" in
        x86_64|amd64)
            IDB_ARCH="amd64"
            ;;
        *)
            log "暂不支持的系统架构: ${arch}"
            exit 1
            ;;
    esac
}

function Prepare_Download_Env() {
    GITHUB_API_URL="${IDB_GITHUB_PROXY:+${IDB_GITHUB_PROXY}/github-api}"
    GITHUB_API_URL="${GITHUB_API_URL:-https://api.github.com}"
    GITHUB_RELEASES_URL="${IDB_GITHUB_PROXY:+${IDB_GITHUB_PROXY}/github-releases}"
    GITHUB_RELEASES_URL="${GITHUB_RELEASES_URL:-https://github.com}"

    if [[ -n "${IDB_GITHUB_PROXY:-}" ]]; then
        log "使用加速代理: ${IDB_GITHUB_PROXY}"
    fi
}

function Download_File() {
    local url="$1"
    local output="$2"

    curl -fL --retry 3 --retry-delay 1 --connect-timeout 10 --progress-bar \
        "${url}" \
        -o "${output}"
}

function Detect_Version() {
    VERSION="${1:-}"
    if [[ -z "${VERSION}" ]]; then
        VERSION=$(Fetch_Latest_Release_Tag "${GITHUB_API_URL}" || true)
    fi
    if [[ -z "${VERSION}" ]]; then
        log "获取目标版本失败"
        exit 1
    fi

    CENTER_PKG="idb_${VERSION}_linux_${IDB_ARCH}.tar.gz"
    AGENT_PKG="idb-agent_${VERSION}_linux_${IDB_ARCH}.tar.gz"
    CENTER_URL="${GITHUB_RELEASES_URL}/sensdata/idb/releases/download/${VERSION}/${CENTER_PKG}"
    AGENT_URL="${GITHUB_RELEASES_URL}/sensdata/idb/releases/download/${VERSION}/${AGENT_PKG}"
}

function Download_Assets() {
    rm -rf "${TMP_DIR}"
    mkdir -p "${TMP_DIR}/center" "${TMP_DIR}/agent"

    log "下载 center 安装包: ${CENTER_PKG}"
    Download_File "${CENTER_URL}" "${TMP_DIR}/${CENTER_PKG}"

    log "下载 agent 安装包: ${AGENT_PKG}"
    Download_File "${AGENT_URL}" "${TMP_DIR}/${AGENT_PKG}"

    tar -xzf "${TMP_DIR}/${CENTER_PKG}" -C "${TMP_DIR}/center"
    tar -xzf "${TMP_DIR}/${AGENT_PKG}" -C "${TMP_DIR}/agent"
}

function Ensure_Config_Value() {
    local file="$1"
    local key="$2"
    local value="$3"

    if grep -q "^${key}=" "${file}" 2>/dev/null; then
        local safe_value
        safe_value=$(printf '%s' "$value" | sed 's/[#&\\/]/\\&/g')
        sed -i "s#^${key}=.*#${key}=${safe_value}#" "${file}"
    else
        printf '%s=%s\n' "${key}" "${value}" >> "${file}"
    fi
}

function Generate_Certs_If_Missing() {
    local cert_file="${IDB_INSTALL_ROOT}/cert.pem"
    local key_file="${IDB_INSTALL_ROOT}/key.pem"

    if [[ -f "${cert_file}" && -f "${key_file}" ]]; then
        return
    fi

    log "生成本地自签名证书"
    openssl req -x509 -nodes -days 3650 \
        -newkey rsa:2048 \
        -keyout "${key_file}" \
        -out "${cert_file}" \
        -subj "/CN=localhost" >/dev/null 2>&1
}

function Resolve_User_Home() {
    local username="$1"
    local user_home=""

    if command -v getent >/dev/null 2>&1; then
        user_home=$(getent passwd "$username" 2>/dev/null | cut -d: -f6)
    fi

    if [[ -z "$user_home" ]]; then
        user_home=$(eval echo "~${username}" 2>/dev/null)
        if [[ "$user_home" == "~${username}" ]]; then
            user_home=""
        fi
    fi

    if [[ -z "$user_home" ]]; then
        user_home=$(sudo -u "$username" -H sh -lc 'printf %s "$HOME"' 2>/dev/null)
    fi

    printf '%s\n' "$user_home"
}

function Configure_Docker_Access() {
    if ! command -v docker >/dev/null 2>&1; then
        return 1
    fi

    if command docker info >/dev/null 2>&1; then
        return 0
    fi

    if [[ -n "${SUDO_USER:-}" && "${SUDO_USER}" != "root" ]]; then
        local docker_home
        docker_home=$(Resolve_User_Home "${SUDO_USER}")
        if [[ -n "$docker_home" ]]; then
            if sudo -u "${SUDO_USER}" -H env HOME="$docker_home" DOCKER_CONFIG="$docker_home/.docker" docker info >/dev/null 2>&1; then
                IDB_DOCKER_USER="${SUDO_USER}"
                IDB_DOCKER_HOME="$docker_home"
                return 0
            fi
        fi
    fi

    return 1
}

function docker() {
    if [[ -n "$IDB_DOCKER_USER" ]]; then
        command sudo -u "$IDB_DOCKER_USER" -H env HOME="$IDB_DOCKER_HOME" DOCKER_CONFIG="$IDB_DOCKER_HOME/.docker" docker "$@"
    else
        command docker "$@"
    fi
}

function Ensure_Directories() {
    mkdir -p "${IDB_INSTALL_ROOT}" "${IDB_HOME_DIR}" "${IDB_DATA_DIR}" "${IDB_AGENT_DIR}" "${IDB_PLUGIN_DIR}"
    mkdir -p "${IDB_LOG_DIR}" "${IDB_RUN_DIR}" "${IDB_CONF_DIR}" "${IDB_AGENT_CONF_DIR}"
}

function Copy_Tree() {
    local src="$1"
    local dst="$2"

    mkdir -p "${dst}"
    cp -R "${src}/." "${dst}/"
}

function Detect_Legacy_Docker_Install() {
    LEGACY_DOCKER_INSTALL="false"

    if ! Configure_Docker_Access; then
        return
    fi

    if docker ps -a --format '{{.Names}}' | grep -qx 'idb'; then
        LEGACY_DOCKER_INSTALL="true"
    fi
}

function Migrate_Docker_Install() {
    local panel_dir="/var/lib/idb"
    local data_dir=""
    local log_dir=""
    local conf_dir=""

    if [[ "${LEGACY_DOCKER_INSTALL}" != "true" ]]; then
        return
    fi

    log "检测到旧版 Docker 部署，开始迁移到原生 center"

    panel_dir=$(docker inspect --format '{{ index .Config.Labels "com.docker.compose.project.working_dir" }}' idb 2>/dev/null || true)
    [[ -z "${panel_dir}" ]] && panel_dir="/var/lib/idb"

    data_dir=$(docker inspect --format '{{ range .Mounts }}{{ if eq .Destination "/var/lib/idb/data" }}{{ .Source }}{{ end }}{{ end }}' idb 2>/dev/null || true)
    log_dir=$(docker inspect --format '{{ range .Mounts }}{{ if eq .Destination "/var/log/idb" }}{{ .Source }}{{ end }}{{ end }}' idb 2>/dev/null || true)
    conf_dir=$(docker inspect --format '{{ range .Mounts }}{{ if eq .Destination "/etc/idb" }}{{ .Source }}{{ end }}{{ end }}' idb 2>/dev/null || true)

    [[ -z "${data_dir}" ]] && data_dir="${IDB_DATA_DIR}"
    [[ -z "${log_dir}" ]] && log_dir="${IDB_LOG_DIR}"
    [[ -z "${conf_dir}" ]] && conf_dir="${IDB_CONF_DIR}"

    local old_image
    old_image=$(docker inspect --format '{{.Config.Image}}' idb 2>/dev/null || true)

    local old_env="${panel_dir}/.env"
    local old_host old_port
    if [[ -f "${old_env}" ]]; then
        old_host=$(grep '^iDB_service_host_ip=' "${old_env}" 2>/dev/null | cut -d'=' -f2)
        old_port=$(grep '^iDB_service_port=' "${old_env}" 2>/dev/null | cut -d'=' -f2)
    fi

    docker stop -t 30 idb >/dev/null 2>&1 || docker kill idb >/dev/null 2>&1 || true
    docker rm -f idb >/dev/null 2>&1 || true

    if [[ -n "${old_image}" ]]; then
        docker rmi "${old_image}" 2>/dev/null || true
        log "已清理旧版 Docker 镜像: ${old_image}"
    fi

    if [[ -d "${conf_dir}" && "${conf_dir}" != "${IDB_CONF_DIR}" ]]; then
        log "迁移配置目录: ${conf_dir} -> ${IDB_CONF_DIR}"
        Copy_Tree "${conf_dir}" "${IDB_CONF_DIR}"
    fi

    if [[ -d "${data_dir}" && "${data_dir}" != "${IDB_DATA_DIR}" ]]; then
        log "迁移数据目录: ${data_dir} -> ${IDB_DATA_DIR}"
        Copy_Tree "${data_dir}" "${IDB_DATA_DIR}"
    fi

    if [[ -d "${log_dir}" && "${log_dir}" != "${IDB_LOG_DIR}" ]]; then
        log "迁移日志目录: ${log_dir} -> ${IDB_LOG_DIR}"
        Copy_Tree "${log_dir}" "${IDB_LOG_DIR}"
    fi

    rm -f "${panel_dir}/docker-compose.yaml" "${panel_dir}/.env"

    if [[ -n "${old_host:-}" ]]; then
        Ensure_Config_Value "${IDB_CONF_DIR}/idb.conf" "host" "${old_host}"
        log "迁移 host 配置: ${old_host}"
    fi
    if [[ -n "${old_port:-}" ]]; then
        Ensure_Config_Value "${IDB_CONF_DIR}/idb.conf" "port" "${old_port}"
        log "迁移 port 配置: ${old_port}"
    fi
}

function Install_Center() {
    local center_dir="${TMP_DIR}/center"
    local config_target="${IDB_CONF_DIR}/idb.conf"

    if [[ ! -f "${center_dir}/idb" || ! -f "${center_dir}/idb.service" || ! -f "${center_dir}/idb.conf" ]]; then
        log "center 安装包内容不完整"
        exit 1
    fi

    if [[ ! -f "${config_target}" ]]; then
        cp "${center_dir}/idb.conf" "${config_target}"
    fi
    Ensure_Config_Value "${config_target}" "github_repo" "sensdata/idb"

    systemctl stop idb.service >/dev/null 2>&1 || true

    cp "${center_dir}/idb" "${IDB_INSTALL_ROOT}/idb"
    chmod +x "${IDB_INSTALL_ROOT}/idb"
    cp "${center_dir}/idb.service" /etc/systemd/system/idb.service
    ln -sf "${IDB_INSTALL_ROOT}/idb" /usr/local/bin/idb

    rm -rf "${IDB_HOME_DIR:?}"/*
    if [[ -d "${center_dir}/home" ]]; then
        cp -R "${center_dir}/home/." "${IDB_HOME_DIR}/"
    fi

    if [[ -d "${center_dir}/plugins" ]]; then
        cp -R "${center_dir}/plugins/." "${IDB_PLUGIN_DIR}/"
        find "${IDB_PLUGIN_DIR}" -type f -exec chmod +x {} \;
    fi
}

function Install_Agent() {
    local agent_dir="${TMP_DIR}/agent"
    local installed_conf="${IDB_AGENT_CONF_DIR}/idb-agent.conf"

    if [[ ! -f "${agent_dir}/idb-agent" || ! -f "${agent_dir}/install-agent.sh" || ! -f "${agent_dir}/idb-agent.conf" ]]; then
        log "agent 安装包内容不完整"
        return 1
    fi

    cp "${TMP_DIR}/${AGENT_PKG}" "${IDB_AGENT_DIR}/idb-agent.tar.gz"
    echo "${VERSION}" > "${IDB_AGENT_DIR}/idb-agent.version"

    if [[ -f "${installed_conf}" ]]; then
        cp "${installed_conf}" "${agent_dir}/idb-agent.conf"
    fi

    chmod +x "${agent_dir}/install-agent.sh"
    (
        cd "${agent_dir}"
        bash ./install-agent.sh
    )
}

function Install_Agent_With_Warning() {
    if ! Install_Agent; then
        AGENT_INSTALL_FAILED="true"
        AGENT_INSTALL_ERROR="本机 agent 安装/升级失败，center 已保留运行，请稍后在面板内重试或检查本机安装环境"
        log "${AGENT_INSTALL_ERROR}"
    fi
}

function Ensure_Admin_Env() {
    local admin_env="${IDB_CONF_DIR}/idb.env"
    touch "${admin_env}"
    chmod 600 "${admin_env}"
}

function Start_Services() {
    systemctl daemon-reload
    systemctl enable idb.service
    systemctl restart idb.service
}

function Cleanup() {
    rm -rf "${TMP_DIR}"
}

function main() {
    trap Cleanup EXIT
    log "======================= 开始升级 ======================="
    Check_Root
    Auto_Detect_Proxy
    Prepare_Download_Env
    Check_Architecture
    Detect_Version "${1:-}"
    Detect_Legacy_Docker_Install
    Download_Assets
    Ensure_Directories
    Migrate_Docker_Install
    Ensure_Admin_Env
    Install_Center
    Generate_Certs_If_Missing
    Start_Services
    Install_Agent_With_Warning
    log "升级完成，版本：${VERSION}"
    if [[ "${AGENT_INSTALL_FAILED}" == "true" ]]; then
        log "升级结果：center 已升级并启动，本机 agent 需要后续处理"
    fi
    log "======================= 升级完成 ======================="
}

main "$@"
