// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.31.1
// source: scriptmanager.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ScriptManager_ListScripts_FullMethodName = "/scriptmanagerpb.ScriptManager/ListScripts"
)

// ScriptManagerClient is the client API for ScriptManager service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ScriptManagerClient interface {
	ListScripts(ctx context.Context, in *ListScriptsRequest, opts ...grpc.CallOption) (*ListScriptsResponse, error)
}

type scriptManagerClient struct {
	cc grpc.ClientConnInterface
}

func NewScriptManagerClient(cc grpc.ClientConnInterface) ScriptManagerClient {
	return &scriptManagerClient{cc}
}

func (c *scriptManagerClient) ListScripts(ctx context.Context, in *ListScriptsRequest, opts ...grpc.CallOption) (*ListScriptsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListScriptsResponse)
	err := c.cc.Invoke(ctx, ScriptManager_ListScripts_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ScriptManagerServer is the server API for ScriptManager service.
// All implementations must embed UnimplementedScriptManagerServer
// for forward compatibility.
type ScriptManagerServer interface {
	ListScripts(context.Context, *ListScriptsRequest) (*ListScriptsResponse, error)
	mustEmbedUnimplementedScriptManagerServer()
}

// UnimplementedScriptManagerServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedScriptManagerServer struct{}

func (UnimplementedScriptManagerServer) ListScripts(context.Context, *ListScriptsRequest) (*ListScriptsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListScripts not implemented")
}
func (UnimplementedScriptManagerServer) mustEmbedUnimplementedScriptManagerServer() {}
func (UnimplementedScriptManagerServer) testEmbeddedByValue()                       {}

// UnsafeScriptManagerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ScriptManagerServer will
// result in compilation errors.
type UnsafeScriptManagerServer interface {
	mustEmbedUnimplementedScriptManagerServer()
}

func RegisterScriptManagerServer(s grpc.ServiceRegistrar, srv ScriptManagerServer) {
	// If the following call pancis, it indicates UnimplementedScriptManagerServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ScriptManager_ServiceDesc, srv)
}

func _ScriptManager_ListScripts_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListScriptsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ScriptManagerServer).ListScripts(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ScriptManager_ListScripts_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ScriptManagerServer).ListScripts(ctx, req.(*ListScriptsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ScriptManager_ServiceDesc is the grpc.ServiceDesc for ScriptManager service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ScriptManager_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "scriptmanagerpb.ScriptManager",
	HandlerType: (*ScriptManagerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListScripts",
			Handler:    _ScriptManager_ListScripts_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "scriptmanager.proto",
}
