// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.1
// source: scriptmanager.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ListScriptsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	HostId        uint32                 `protobuf:"varint,1,opt,name=host_id,json=hostId,proto3" json:"host_id,omitempty"`
	Type          string                 `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	Category      string                 `protobuf:"bytes,3,opt,name=category,proto3" json:"category,omitempty"`
	Page          int32                  `protobuf:"varint,4,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,5,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListScriptsRequest) Reset() {
	*x = ListScriptsRequest{}
	mi := &file_scriptmanager_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListScriptsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListScriptsRequest) ProtoMessage() {}

func (x *ListScriptsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_scriptmanager_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListScriptsRequest.ProtoReflect.Descriptor instead.
func (*ListScriptsRequest) Descriptor() ([]byte, []int) {
	return file_scriptmanager_proto_rawDescGZIP(), []int{0}
}

func (x *ListScriptsRequest) GetHostId() uint32 {
	if x != nil {
		return x.HostId
	}
	return 0
}

func (x *ListScriptsRequest) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *ListScriptsRequest) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

func (x *ListScriptsRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListScriptsRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type ListScriptsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Scripts       []string               `protobuf:"bytes,1,rep,name=scripts,proto3" json:"scripts,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListScriptsResponse) Reset() {
	*x = ListScriptsResponse{}
	mi := &file_scriptmanager_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListScriptsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListScriptsResponse) ProtoMessage() {}

func (x *ListScriptsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_scriptmanager_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListScriptsResponse.ProtoReflect.Descriptor instead.
func (*ListScriptsResponse) Descriptor() ([]byte, []int) {
	return file_scriptmanager_proto_rawDescGZIP(), []int{1}
}

func (x *ListScriptsResponse) GetScripts() []string {
	if x != nil {
		return x.Scripts
	}
	return nil
}

var File_scriptmanager_proto protoreflect.FileDescriptor

const file_scriptmanager_proto_rawDesc = "" +
	"\n" +
	"\x13scriptmanager.proto\x12\x0fscriptmanagerpb\"\x8e\x01\n" +
	"\x12ListScriptsRequest\x12\x17\n" +
	"\ahost_id\x18\x01 \x01(\rR\x06hostId\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\x12\x1a\n" +
	"\bcategory\x18\x03 \x01(\tR\bcategory\x12\x12\n" +
	"\x04page\x18\x04 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x05 \x01(\x05R\bpageSize\"/\n" +
	"\x13ListScriptsResponse\x12\x18\n" +
	"\ascripts\x18\x01 \x03(\tR\ascripts2i\n" +
	"\rScriptManager\x12X\n" +
	"\vListScripts\x12#.scriptmanagerpb.ListScriptsRequest\x1a$.scriptmanagerpb.ListScriptsResponseB\x06Z\x04./pbb\x06proto3"

var (
	file_scriptmanager_proto_rawDescOnce sync.Once
	file_scriptmanager_proto_rawDescData []byte
)

func file_scriptmanager_proto_rawDescGZIP() []byte {
	file_scriptmanager_proto_rawDescOnce.Do(func() {
		file_scriptmanager_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_scriptmanager_proto_rawDesc), len(file_scriptmanager_proto_rawDesc)))
	})
	return file_scriptmanager_proto_rawDescData
}

var file_scriptmanager_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_scriptmanager_proto_goTypes = []any{
	(*ListScriptsRequest)(nil),  // 0: scriptmanagerpb.ListScriptsRequest
	(*ListScriptsResponse)(nil), // 1: scriptmanagerpb.ListScriptsResponse
}
var file_scriptmanager_proto_depIdxs = []int32{
	0, // 0: scriptmanagerpb.ScriptManager.ListScripts:input_type -> scriptmanagerpb.ListScriptsRequest
	1, // 1: scriptmanagerpb.ScriptManager.ListScripts:output_type -> scriptmanagerpb.ListScriptsResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_scriptmanager_proto_init() }
func file_scriptmanager_proto_init() {
	if File_scriptmanager_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_scriptmanager_proto_rawDesc), len(file_scriptmanager_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_scriptmanager_proto_goTypes,
		DependencyIndexes: file_scriptmanager_proto_depIdxs,
		MessageInfos:      file_scriptmanager_proto_msgTypes,
	}.Build()
	File_scriptmanager_proto = out.File
	file_scriptmanager_proto_goTypes = nil
	file_scriptmanager_proto_depIdxs = nil
}
